package openapi

import (
	"encoding/json"
	"fmt"
	htemplate "html/template"
	"maps"
	"slices"
	"strings"
	"sync"

	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/utils/v2"
	utilsstrings "github.com/gofiber/utils/v2/strings"
)

// maxCachedSwaggerPages bounds the per-target Swagger UI page cache so that a
// parameterized mount prefix (one target per parameter value) cannot grow the
// cache without limit. The same bound applies to the per-app cache map.
const maxCachedSwaggerPages = 32

// maxPathVariants bounds the optional-parameter expansion in
// buildOpenAPIPathVariants, which is otherwise exponential in the number of
// optional parameters on a single route.
const maxPathVariants = 64

// appCache holds one app's generated artifacts. The spec bytes do not depend
// on the target path (only on the routes and config), so a single entry
// suffices no matter how many prefixes the handler serves; the Swagger UI
// pages embed the spec URL and stay keyed per target.
type appCache struct {
	uiPages  map[string][]byte
	specData []byte
	specRev  uint64
}

// New creates a new middleware handler that serves the generated OpenAPI specification.
func New(config ...Config) fiber.Handler {
	cfg := configDefault(config...)

	// Caches are scoped per *fiber.App: the same handler value may be
	// registered on several apps, and one app's spec or revision counter must
	// never validate another app's cached bytes.
	var (
		cacheMu sync.Mutex
		caches  = make(map[*fiber.App]*appCache)
	)

	// cacheFor returns the app's cache entry, creating it on first use. Past
	// the bound the entry is still returned but not retained. The caller must
	// hold cacheMu.
	cacheFor := func(app *fiber.App) *appCache {
		cache, ok := caches[app]
		if !ok {
			cache = &appCache{uiPages: make(map[string][]byte)}
			if len(caches) < maxCachedSwaggerPages {
				caches[app] = cache
			}
		}
		return cache
	}

	// specBytes returns the app's cached specification, regenerating it when the
	// route revision moved. The lock is released with defer so a panic in
	// GetRoutes, generateSpec or a user-supplied JSONEncoder cannot wedge the
	// cache for every app this handler serves.
	specBytes := func(app *fiber.App) ([]byte, error) {
		cacheMu.Lock()
		defer cacheMu.Unlock()

		cache := cacheFor(app)
		rev := app.RoutesRevision()
		if cache.specData == nil || cache.specRev != rev {
			// GetRoutes returns deep copies taken under the router lock, so
			// spec generation never races route registration or the
			// documentation helpers.
			spec := generateSpec(app.GetRoutes(), &cfg)
			data, err := app.Config().JSONEncoder(spec)
			if err != nil {
				return nil, fmt.Errorf("openapi: marshal spec: %w", err)
			}
			cache.specData, cache.specRev = data, rev
		}
		return cache.specData, nil
	}

	// uiBytes returns the app's cached Swagger UI page for targetPath, building
	// it on first use. Same defer rationale as specBytes.
	uiBytes := func(app *fiber.App, targetPath string) ([]byte, error) {
		cacheMu.Lock()
		defer cacheMu.Unlock()

		cache := cacheFor(app)
		if data, ok := cache.uiPages[targetPath]; ok {
			return data, nil
		}
		data, err := buildSwaggerUIPage(targetPath, &cfg, app.Config().JSONEncoder)
		if err != nil {
			return nil, fmt.Errorf("openapi: build swagger ui page: %w", err)
		}
		if len(cache.uiPages) >= maxCachedSwaggerPages {
			// The keys come from the request path under a parameterized mount,
			// so they are attacker-controlled; drop the oldest-inserted entries
			// rather than letting junk keys pin the cache and force a rebuild
			// on every later request.
			clear(cache.uiPages)
		}
		cache.uiPages[targetPath] = data
		return data, nil
	}

	specPath := utils.TrimRight(normalizedPath(cfg.Path), '/')
	uiPath := utils.TrimRight(normalizedPath(cfg.UIPath), '/')

	return func(c fiber.Ctx) error {
		if cfg.Next != nil && cfg.Next(c) {
			return c.Next()
		}

		if c.Method() != fiber.MethodGet && c.Method() != fiber.MethodHead {
			return c.Next()
		}

		equal := utils.EqualFold[string]
		if c.App().Config().CaseSensitive {
			equal = stringsEqual
		}

		request := utils.TrimRight(c.Path(), '/')
		route := c.Route()
		isMiddleware := route != nil && route.IsMiddleware()

		// Fast path for prefix-mounted middleware: most requests cannot match
		// either target, so skip target resolution without allocating.
		if isMiddleware && !hasSuffix(request, specPath, equal) && !hasSuffix(request, uiPath, equal) {
			return c.Next()
		}

		targets := resolveTargets(c, specPath, uiPath, equal)

		switch {
		case targets.specOK && equal(request, targets.spec):
			// The generated bytes are cached once per app and invalidated by
			// the app's route revision, so route additions, removals, and
			// metadata changes are always reflected without regenerating on
			// every request.
			data, err := specBytes(c.App())
			if err != nil {
				return err
			}

			c.Set(fiber.HeaderContentType, fiber.MIMEApplicationJSONCharsetUTF8)
			return c.Status(fiber.StatusOK).Send(data)
		case targets.uiOK && equal(request, targets.ui):
			data, err := uiBytes(c.App(), targets.spec)
			if err != nil {
				return err
			}

			c.Set(fiber.HeaderContentType, fiber.MIMETextHTMLCharsetUTF8)
			return c.Status(fiber.StatusOK).Send(data)
		default:
			return c.Next()
		}
	}
}

func stringsEqual(a, b string) bool { return a == b }

// hasSuffix reports whether s ends with suffix under the given equality
// function (exact or case-folding).
func hasSuffix(s, suffix string, equal func(a, b string) bool) bool {
	return len(s) >= len(suffix) && equal(s[len(s)-len(suffix):], suffix)
}

// specTargets holds the paths this handler answers on for the current request.
// The ok flags are explicit rather than encoded as an empty path, because an
// empty path is itself meaningful: it is what a root target ("/") trims to.
type specTargets struct {
	spec   string
	ui     string
	specOK bool
	uiOK   bool
}

// resolveTargets derives the spec and UI target paths (trailing slashes
// trimmed) for the current request from the route the handler runs on.
//
// For prefix middleware the targets live directly under the mount prefix, and a
// mount whose own prefix ends in a configured path IS that target. For an exact
// method route (e.g. app.Get("/openapi.json", openapi.New()), possibly cloned
// under a mount prefix) the registered path itself is the target: the
// configured suffix decides whether it serves the spec or the UI, and a fixed
// custom path matching neither serves the specification.
func resolveTargets(c fiber.Ctx, specPath, uiPath string, equal func(a, b string) bool) specTargets {
	route := c.Route()
	if route == nil {
		return specTargets{spec: specPath, ui: uiPath, specOK: true, uiOK: true}
	}

	if !route.IsMiddleware() {
		// The route matched exactly, so the request path IS the concrete
		// registered path — including values of any parameters the pattern
		// carries (e.g. an exact route cloned under a parameterized mount
		// prefix).
		path := utils.TrimRight(c.Path(), '/')
		switch {
		case specPath != "" && hasSuffix(path, specPath, equal):
			base := path[:len(path)-len(specPath)]
			return specTargets{spec: path, ui: base + uiPath, specOK: true, uiOK: uiPath != ""}
		case uiPath != "" && hasSuffix(path, uiPath, equal):
			base := path[:len(path)-len(uiPath)]
			return specTargets{spec: base + specPath, ui: path, specOK: true, uiOK: true}
		case len(route.Params) == 0:
			// A fixed custom path (app.Get("/docs", openapi.New())) serves the
			// specification.
			return specTargets{spec: path, specOK: true}
		default:
			// A wildcard or parameterized registration matches paths the author
			// never enumerated, so serving the document at every one of them
			// would leak the whole route inventory. Only the exact suffix
			// matches above are honored.
			return specTargets{}
		}
	}

	prefix := routePrefix(route.Path, c.Path())
	switch {
	case specPath != "" && hasSuffix(prefix, specPath, equal):
		// e.g. app.Use("/v1/openapi.json", openapi.New()): the mount itself is
		// the spec target; the UI, if enabled, sits beside it.
		base := prefix[:len(prefix)-len(specPath)]
		return specTargets{spec: prefix, ui: base + uiPath, specOK: true, uiOK: uiPath != ""}
	case uiPath != "" && hasSuffix(prefix, uiPath, equal):
		// e.g. app.Use("/swagger", openapi.New()): the mount itself is the UI.
		// The spec has to stay *under* the mount, otherwise the page that is
		// served here could never load the document it points at.
		return specTargets{spec: prefix + specPath, ui: prefix, specOK: true, uiOK: true}
	default:
		return specTargets{spec: prefix + specPath, ui: prefix + uiPath, specOK: true, uiOK: true}
	}
}

type swaggerUITemplateData struct {
	SwaggerOptionsJSON         string
	Title                      string
	OpenAPIURL                 string
	SwaggerCSSURL              string
	SwaggerBundleURL           string
	SwaggerStandalonePresetURL string
}

var swaggerUITemplate = htemplate.Must(htemplate.New("swagger-ui").Parse(`<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{{ .Title }} - Swagger UI</title>
    <link
      rel="stylesheet"
      href="{{ .SwaggerCSSURL }}"
    />
  </head>
  <body>
    <div id="swagger-ui" data-swagger-options='{{ .SwaggerOptionsJSON }}'></div>

    <script
      src="{{ .SwaggerBundleURL }}"
      crossorigin="anonymous"
    ></script>
    {{ if .SwaggerStandalonePresetURL }}<script
      src="{{ .SwaggerStandalonePresetURL }}"
      crossorigin="anonymous"
    ></script>{{ end }}
    <script>
      window.addEventListener("load", function () {
        const options = JSON.parse(document.getElementById("swagger-ui").dataset.swaggerOptions);

        const presets = [SwaggerUIBundle.presets.apis];
        const config = {
          url: "{{ .OpenAPIURL }}",
          dom_id: "#swagger-ui",
          persistAuthorization: true,
        };
        if (typeof SwaggerUIStandalonePreset !== "undefined") {
          presets.push(SwaggerUIStandalonePreset);
          config.layout = "StandaloneLayout";
        }
        config.presets = presets;

        window.ui = SwaggerUIBundle({
          ...config,
          ...options,
        });
      });
    </script>
  </body>
</html>
`))

// buildSwaggerUIPage renders the Swagger UI page for the given spec URL. The
// options are marshaled with the app's configured JSON encoder — the same one
// that encodes the spec — so one middleware never mixes encoders;
// html/template escapes the embedded JSON regardless of the encoder.
func buildSwaggerUIPage(openAPIURL string, cfg *Config, encode utils.JSONMarshal) ([]byte, error) {
	if encode == nil {
		encode = json.Marshal
	}
	swaggerOptionsJSON, err := encode(cfg.SwaggerOptions)
	if err != nil {
		return nil, fmt.Errorf("marshal swagger options: %w", err)
	}
	if len(swaggerOptionsJSON) == 0 || string(swaggerOptionsJSON) == "null" {
		swaggerOptionsJSON = []byte("{}")
	}

	data := swaggerUITemplateData{
		Title:                      cfg.Title,
		OpenAPIURL:                 openAPIURL,
		SwaggerCSSURL:              cfg.SwaggerCSSURL,
		SwaggerBundleURL:           cfg.SwaggerBundleURL,
		SwaggerStandalonePresetURL: cfg.SwaggerStandalonePresetURL,
		SwaggerOptionsJSON:         string(swaggerOptionsJSON),
	}

	var builder strings.Builder
	if err := swaggerUITemplate.Execute(&builder, data); err != nil {
		return nil, fmt.Errorf("execute swagger ui template: %w", err)
	}

	return []byte(builder.String()), nil
}

// normalizedPath returns cfgPath with a leading slash. Defaults for empty
// paths are applied earlier by configDefault.
func normalizedPath(cfgPath string) string {
	if !strings.HasPrefix(cfgPath, "/") {
		return "/" + cfgPath
	}
	return cfgPath
}

// routeTokens returns the segment's routing-relevant characters: escaped
// characters and <constraint> spans are dropped, mirroring path.go's escape
// and constraint rules, so a literal "\+" or a "+" inside a regex constraint
// (e.g. ":id<regex([0-9]+)>") is never mistaken for a routing token.
//
// TODO: replace this re-lexing (and buildOpenAPIPathVariants') with the
// router's own parsed segments once path.go exposes them.
func routeTokens(seg string) string {
	var b strings.Builder
	inConstraint := false
	for i := 0; i < len(seg); i++ {
		switch ch := seg[i]; {
		case ch == '\\':
			i++ // the escaped character is a literal
		case inConstraint:
			if ch == '>' {
				inConstraint = false
			}
		case ch == '<':
			inConstraint = true
		default:
			_ = b.WriteByte(ch) //nolint:errcheck // strings.Builder.WriteByte never returns an error
		}
	}
	return b.String()
}

// openAPIOperationMethods is the set of HTTP methods the Path Item Object can
// express. CONNECT is deliberately absent: OpenAPI defines no `connect`
// operation. `query` is 3.2-only and gated separately by the caller.
var openAPIOperationMethods = map[string]struct{}{
	fiber.MethodGet:     {},
	fiber.MethodHead:    {},
	fiber.MethodPost:    {},
	fiber.MethodPut:     {},
	fiber.MethodPatch:   {},
	fiber.MethodDelete:  {},
	fiber.MethodOptions: {},
	fiber.MethodTrace:   {},
	fiber.MethodQuery:   {},
}

// isOpenAPIOperationMethod reports whether method maps to a Path Item
// operation key.
func isOpenAPIOperationMethod(method string) bool {
	_, ok := openAPIOperationMethods[method]
	return ok
}

// normalizePathHierarchy blanks every template expression in an OpenAPI path
// ("/files/{dir}" → "/files/{}"), so paths identical up to parameter names
// share one key.
func normalizePathHierarchy(path string) string {
	var b strings.Builder
	b.Grow(len(path))
	inTemplate := false
	for i := 0; i < len(path); i++ {
		switch ch := path[i]; {
		case inTemplate:
			if ch == '}' {
				inTemplate = false
				_, _ = b.WriteString("{}") //nolint:errcheck // strings.Builder.WriteString never returns an error
			}
		case ch == '{':
			inTemplate = true
		default:
			_ = b.WriteByte(ch) //nolint:errcheck // strings.Builder.WriteByte never returns an error
		}
	}
	return b.String()
}

// routePrefix derives the concrete mount prefix of a middleware route for the
// current request. A static prefix is the route path itself (with escape
// characters removed, matching the request form). When the prefix pattern
// contains parameters (e.g. app.Use("/:tenant", openapi.New())), the concrete
// values are taken from the request path, consuming one request segment per
// pattern segment; greedy wildcards and optional parameters make the prefix
// length ambiguous and end it.
func routePrefix(pattern, requestPath string) string {
	pattern = utils.TrimRight(pattern, '/')
	if pattern == "" {
		return ""
	}

	// Classify segments by routing tokens only: constraints and escaped
	// characters are literals.
	parameterized := false
	segments := 0
	counting := true
	for seg := range strings.SplitSeq(strings.TrimPrefix(pattern, "/"), "/") {
		tokens := routeTokens(seg)
		if strings.ContainsAny(tokens, ":*+") || strings.HasSuffix(tokens, "?") {
			parameterized = true
		}
		if counting && (seg == "" || strings.ContainsAny(tokens, "*+") || strings.HasSuffix(tokens, "?")) {
			counting = false
		}
		if counting {
			segments++
		}
	}
	if !parameterized {
		// Static prefix: serve it in its unescaped (request) form.
		return utils.TrimRight(fiber.RemoveEscapeChar(pattern), '/')
	}
	if segments == 0 {
		return ""
	}

	idx := 0
	for range segments {
		if idx+1 >= len(requestPath) {
			return requestPath
		}
		next := strings.IndexByte(requestPath[idx+1:], '/')
		if next < 0 {
			// The request path ends inside the prefix (e.g. a request for the
			// bare mount path).
			return requestPath
		}
		idx += 1 + next
	}
	return requestPath[:idx]
}

type openAPISpec struct {
	Paths             map[string]map[string]operation `json:"paths"`
	Components        map[string]any                  `json:"components,omitempty"`
	Webhooks          map[string]any                  `json:"webhooks,omitempty"`
	ExternalDocs      *ExternalDocs                   `json:"externalDocs,omitempty"` //nolint:tagliatelle // OpenAPI spec uses camelCase
	Info              openAPIInfo                     `json:"info"`
	OpenAPI           string                          `json:"openapi"`
	Self              string                          `json:"$self,omitempty"`
	JSONSchemaDialect string                          `json:"jsonSchemaDialect,omitempty"` //nolint:tagliatelle // OpenAPI spec uses camelCase
	Servers           []Server                        `json:"servers,omitempty"`
	Security          []map[string][]string           `json:"security,omitempty"`
	Tags              []Tag                           `json:"tags,omitempty"`
}

type openAPIInfo struct {
	Contact        *Contact `json:"contact,omitempty"`
	License        *License `json:"license,omitempty"`
	Title          string   `json:"title"`
	Version        string   `json:"version"`
	Summary        string   `json:"summary,omitempty"`
	Description    string   `json:"description,omitempty"`
	TermsOfService string   `json:"termsOfService,omitempty"` //nolint:tagliatelle // OpenAPI spec uses camelCase
}

type operation struct {
	Responses    map[string]response `json:"responses"`
	RequestBody  *requestBody        `json:"requestBody,omitempty"`  //nolint:tagliatelle // OpenAPI spec uses camelCase
	ExternalDocs map[string]any      `json:"externalDocs,omitempty"` //nolint:tagliatelle // OpenAPI spec uses camelCase
	// extensions holds arbitrary operation-object fields (servers, callbacks,
	// x-* extensions) merged at marshal time. Excluded from normal marshaling.
	extensions map[string]any

	OperationID string `json:"operationId,omitempty"` //nolint:tagliatelle // OpenAPI spec uses camelCase
	Summary     string `json:"summary"`
	// description is optional in the Operation Object, so an undocumented
	// operation omits the key instead of emitting an empty string.
	Description string `json:"description,omitempty"`

	Parameters []parameter           `json:"parameters,omitempty"`
	Tags       []string              `json:"tags,omitempty"`
	Security   []map[string][]string `json:"security,omitempty"`

	Deprecated bool `json:"deprecated,omitempty"`
}

// MarshalJSON merges operation extensions into the operation object without
// clobbering generated keys.
//
//nolint:gocritic // hugeParam: a value receiver is required so map values (which are not addressable) are marshaled through this method
func (o operation) MarshalJSON() ([]byte, error) {
	type alias operation
	base, err := json.Marshal(alias(o))
	if err != nil {
		return nil, fmt.Errorf("openapi: marshal operation: %w", err)
	}
	if len(o.extensions) == 0 {
		return base, nil
	}
	// Splice the extensions into the already-encoded object rather than
	// decoding it into map[string]any and re-encoding it: that round trip
	// turns every number in the operation into a float64 and silently loses
	// integer precision past 2^53.
	var existing map[string]json.RawMessage
	if err = json.Unmarshal(base, &existing); err != nil {
		return nil, fmt.Errorf("openapi: merge operation extensions: %w", err)
	}

	keys := make([]string, 0, len(o.extensions))
	for key := range o.extensions {
		if _, taken := existing[key]; taken {
			continue
		}
		keys = append(keys, key)
	}
	if len(keys) == 0 {
		return base, nil
	}
	// Sorted so the generated document is byte-stable across runs.
	slices.Sort(keys)

	// Encode first and size the buffer by summing the parts, so the capacity is
	// exact and the computation cannot overflow.
	type extensionPair struct{ key, value []byte }
	pairs := make([]extensionPair, 0, len(keys))
	size := len(base)
	for _, key := range keys {
		encodedKey, kErr := json.Marshal(key)
		if kErr != nil {
			return nil, fmt.Errorf("openapi: marshal operation extension key %q: %w", key, kErr)
		}
		encodedValue, vErr := json.Marshal(o.extensions[key])
		if vErr != nil {
			return nil, fmt.Errorf("openapi: marshal operation extension %q: %w", key, vErr)
		}
		pairs = append(pairs, extensionPair{key: encodedKey, value: encodedValue})
		size += len(encodedKey) + len(encodedValue) + 2 // ':' separator and ',' delimiter
	}

	out := make([]byte, 0, size)
	out = append(out, base[:len(base)-1]...) // everything but the closing brace
	for _, pair := range pairs {
		if len(out) > 1 {
			out = append(out, ',')
		}
		out = append(out, pair.key...)
		out = append(out, ':')
		out = append(out, pair.value...)
	}
	out = append(out, '}')
	return out, nil
}

type response struct {
	Content     map[string]map[string]any `json:"content,omitempty"`
	Headers     map[string]any            `json:"headers,omitempty"`
	Links       map[string]any            `json:"links,omitempty"`
	Description string                    `json:"description"`
}

type parameter struct {
	Schema          map[string]any            `json:"schema,omitempty"`
	Content         map[string]map[string]any `json:"content,omitempty"`
	Example         any                       `json:"example,omitempty"`
	Examples        map[string]any            `json:"examples,omitempty"`
	Explode         *bool                     `json:"explode,omitempty"`
	Description     string                    `json:"description,omitempty"`
	Name            string                    `json:"name"`
	In              string                    `json:"in"`
	Style           string                    `json:"style,omitempty"`
	Required        bool                      `json:"required"`
	Deprecated      bool                      `json:"deprecated,omitempty"`
	AllowEmptyValue bool                      `json:"allowEmptyValue,omitempty"` //nolint:tagliatelle // OpenAPI spec uses camelCase
	AllowReserved   bool                      `json:"allowReserved,omitempty"`   //nolint:tagliatelle // OpenAPI spec uses camelCase
}

type requestBody struct {
	Content     map[string]map[string]any `json:"content"`
	Description string                    `json:"description,omitempty"`
	Required    bool                      `json:"required,omitempty"`
}

type pathVariant struct {
	PathParamAliases map[string]string
	// ParamConstraints maps an emitted path parameter name to the raw text of
	// its route-pattern "<...>" constraint span, when it had one.
	ParamConstraints map[string]string
	Path             string
	ParamNames       []string
}

type resolvedParamName struct {
	openAPI string
	raw     string
}

const wildcardParamName = "wildcard"

const (
	paramLocationPath = "path"
	// paramLocationQuerystring is the OpenAPI 3.2 location that describes the
	// entire query string as one value. It must be paired with "content".
	paramLocationQuerystring = "querystring"
	// querystringMediaType is the media type used to wrap a querystring
	// parameter's schema when the author supplied no explicit content map.
	querystringMediaType = "application/x-www-form-urlencoded"

	schemaKeyType     = "type"
	schemaKeyFormat   = "format"
	schemaTypeString  = "string"
	schemaTypeObject  = "object"
	schemaTypeBoolean = "boolean"
	schemaTypeInteger = "integer"
	schemaTypeNumber  = "number"
)

// generateOperationID derives a stable, readable operationId from an HTTP method
// and an OpenAPI path, e.g. ("GET", "/users/{id}") -> "getUsersId". It is used
// when a route has no explicit Name.
func generateOperationID(method, path string) string {
	var b strings.Builder
	_, _ = b.WriteString(utilsstrings.ToLower(method)) //nolint:errcheck // strings.Builder.WriteString never returns an error
	capNext := true
	for i := 0; i < len(path); i++ {
		c := path[i]
		switch {
		case c >= 'a' && c <= 'z':
			if capNext {
				c -= 'a' - 'A'
				capNext = false
			}
			_ = b.WriteByte(c) //nolint:errcheck // strings.Builder.WriteByte never returns an error
		case (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9'):
			capNext = false
			_ = b.WriteByte(c) //nolint:errcheck // strings.Builder.WriteByte never returns an error
		default:
			capNext = true
		}
	}
	return b.String()
}

// uniqueOperationID returns id when unused, otherwise appends a numeric suffix
// until the result is unique, recording the chosen value in used so the
// generated document never repeats an operationId.
func uniqueOperationID(id string, used map[string]struct{}) string {
	if id == "" {
		id = "operation"
	}
	candidate := id
	for i := 2; ; i++ {
		if _, exists := used[candidate]; !exists {
			used[candidate] = struct{}{}
			return candidate
		}
		candidate = fmt.Sprintf("%s_%d", id, i)
	}
}

// openAPIVersionRank orders the supported OpenAPI versions for comparison.
var openAPIVersionRank = map[string]int{
	versionOpenAPI30: 0,
	versionOpenAPI31: 1,
	versionOpenAPI32: 2,
}

// versionAtLeast reports whether version is greater than or equal to minimum.
func versionAtLeast(version, minimum string) bool {
	return openAPIVersionRank[version] >= openAPIVersionRank[minimum]
}

// generateSpec builds the OpenAPI document from a snapshot of routes (deep
// copies from App.GetRoutes, safe to read without further locking).
func generateSpec(routes []fiber.Route, cfg *Config) openAPISpec {
	paths := make(map[string]map[string]operation)
	// usedOperationIDs guarantees operationId uniqueness across the document,
	// which the OpenAPI specification requires.
	usedOperationIDs := make(map[string]struct{})
	// hierarchyPaths maps a path template with its parameter names blanked
	// ("/users/{}") to the concrete path already published for it. The OpenAPI
	// spec forbids two templated paths that differ only in parameter names, and
	// the rule is per document, not per method — so a later operation on the
	// same hierarchy joins the path item that already exists instead of
	// creating a second, forbidden one.
	hierarchyPaths := make(map[string]canonicalPathItem)

	for i := range routes {
		r := &routes[i]
		// The Path Item Object defines a fixed set of operation keys, so a
		// route registered under a custom method (fiber.Config.RequestMethods
		// accepts any verb) has no valid representation and is skipped rather
		// than emitted as an invalid key. CONNECT is standard but has no
		// OpenAPI operation either.
		if !isOpenAPIOperationMethod(r.Method) {
			continue
		}
		// The OpenAPI `query` operation key exists only in 3.2+; skip QUERY
		// routes for earlier versions, where it cannot be represented.
		if r.Method == fiber.MethodQuery && !versionAtLeast(cfg.OpenAPIVersion, versionOpenAPI32) {
			continue
		}
		// Skip middleware routes registered via Use()
		if r.IsMiddleware() {
			continue
		}
		// Skip automatically generated HEAD routes
		if r.IsAutoHead() {
			continue
		}
		// Skip routes explicitly excluded from the spec via Hidden()
		if r.IsHidden() {
			continue
		}

		variants := buildOpenAPIPathVariants(r.Path, r.Params)
		for _, variant := range variants {
			methodLower := utilsstrings.ToLower(r.Method)
			// The router dispatches to the first matching route, so when two
			// routes produce the same path+method (e.g. an optional-parameter
			// variant colliding with an explicitly registered path), the
			// earlier registration describes the observable behavior and the
			// later one must not overwrite its documentation.
			if _, exists := paths[variant.Path][methodLower]; exists {
				continue
			}
			// Templated paths identical up to parameter names (e.g.
			// /files/{dir} vs /files/{name} from two optional parameters)
			// MUST NOT coexist per the OpenAPI spec, and the router would
			// never dispatch to the later one anyway — first emitted wins.
			hierarchy := normalizePathHierarchy(variant.Path)
			if canonical, exists := hierarchyPaths[hierarchy]; exists {
				// Another route already published this hierarchy under a
				// different parameter name; emit into that path item, and drop
				// the operation if the method is taken there too.
				if canonical.path != variant.Path {
					if _, taken := paths[canonical.path][methodLower]; taken {
						continue
					}
					// The operation moves onto the canonical template, so its
					// parameters have to move with it: declaring "name" under a
					// path that reads "{id}" leaves the template parameter
					// undeclared and the document invalid.
					adoptCanonicalParamNames(&variant, canonical.params)
					variant.Path = canonical.path
				}
			} else {
				hierarchyPaths[hierarchy] = canonicalPathItem{
					path:   variant.Path,
					params: variant.ParamNames,
				}
			}

			params := make([]parameter, 0, len(variant.ParamNames))
			paramIndex := make(map[string]int, len(variant.ParamNames))
			for _, p := range variant.ParamNames {
				param := parameter{
					Name:     p,
					In:       paramLocationPath,
					Required: true,
					// A "<...>" constraint in the route pattern narrows the
					// values the router accepts, so the schema reflects it
					// instead of typing every path parameter as a string.
					Schema: pathParamSchema(variant.ParamConstraints[p]),
				}
				params = append(params, param)
				paramIndex[param.In+":"+param.Name] = len(params) - 1
			}

			extras := remapRouteParameters(r.Parameters, variant.PathParamAliases, variant.ParamNames)
			// The "querystring" location only exists in OpenAPI 3.2+;
			// emitting it for earlier versions would make the document
			// invalid.
			if !versionAtLeast(cfg.OpenAPIVersion, versionOpenAPI32) {
				extras = dropQuerystringParameters(extras)
			}
			params = mergeRouteParameters(params, paramIndex, extras)

			summary := r.Summary
			if summary == "" {
				summary = r.Method + " " + variant.Path
			}
			description := r.Description

			operationID := r.Name
			if operationID == "" {
				operationID = generateOperationID(r.Method, variant.Path)
			}
			operationID = uniqueOperationID(operationID, usedOperationIDs)

			respType := r.Produces

			responses := convertRouteResponses(r.Responses, respType)
			if len(responses) == 0 {
				status, defaultResp := defaultResponseForMethod(r.Method, respType)
				responses = map[string]response{status: defaultResp}
			}

			reqBody := buildRequestBody(r.RequestBody)
			if reqBody == nil {
				reqType := r.Consumes
				if shouldIncludeRequestBody(reqType, r) {
					reqBody = &requestBody{Content: map[string]map[string]any{reqType: {}}}
				}
			}
			// GET and HEAD operations never carry a request body, and a
			// TRACE request MUST NOT include content (RFC 9110).
			if r.Method == fiber.MethodGet || r.Method == fiber.MethodHead || r.Method == fiber.MethodTrace {
				reqBody = nil
			}

			if paths[variant.Path] == nil {
				paths[variant.Path] = make(map[string]operation)
			}

			paths[variant.Path][methodLower] = operation{
				OperationID:  operationID,
				Summary:      summary,
				Description:  description,
				Tags:         r.Tags,
				Deprecated:   r.Deprecated,
				Parameters:   params,
				RequestBody:  reqBody,
				Responses:    responses,
				Security:     r.Security,
				ExternalDocs: maps.Clone(r.ExternalDocs),
				extensions:   maps.Clone(r.OperationExtensions),
			}
		}
	}

	spec := openAPISpec{
		OpenAPI: cfg.OpenAPIVersion,
		Info: openAPIInfo{
			Title:          cfg.Title,
			Version:        cfg.Version,
			Description:    cfg.Description,
			TermsOfService: cfg.TermsOfService,
			Contact:        cfg.Contact,
			License:        cfg.License,
		},
		Paths: paths,
	}

	spec.Servers = buildServers(cfg)

	if len(cfg.Security) > 0 {
		spec.Security = cfg.Security
	}

	if len(cfg.Tags) > 0 {
		spec.Tags = append([]Tag(nil), cfg.Tags...)
	}

	if cfg.ExternalDocs != nil {
		spec.ExternalDocs = &ExternalDocs{
			Description: cfg.ExternalDocs.Description,
			URL:         cfg.ExternalDocs.URL,
		}
	}

	// license.identifier (SPDX) requires OpenAPI 3.1+. Drop it for 3.0 without
	// mutating the caller's License.
	if cfg.License != nil && cfg.License.Identifier != "" && !versionAtLeast(cfg.OpenAPIVersion, versionOpenAPI31) {
		licenseCopy := *cfg.License
		licenseCopy.Identifier = ""
		spec.Info.License = &licenseCopy
	}

	// OpenAPI 3.1+ document fields.
	if versionAtLeast(cfg.OpenAPIVersion, versionOpenAPI31) {
		spec.Info.Summary = cfg.Summary
		spec.JSONSchemaDialect = cfg.JSONSchemaDialect
		if len(cfg.Webhooks) > 0 {
			spec.Webhooks = maps.Clone(cfg.Webhooks)
		}
	}

	// OpenAPI 3.2+ document fields.
	if versionAtLeast(cfg.OpenAPIVersion, versionOpenAPI32) {
		spec.Self = cfg.Self
	}

	spec.Components = buildComponents(cfg)

	return spec
}

// buildServers resolves the server list, preferring Config.Servers and falling
// back to the single Config.ServerURL for backward compatibility.
func buildServers(cfg *Config) []Server {
	// Server.name is an OpenAPI 3.2+ field.
	allowName := versionAtLeast(cfg.OpenAPIVersion, versionOpenAPI32)
	if len(cfg.Servers) > 0 {
		servers := make([]Server, 0, len(cfg.Servers))
		for _, server := range cfg.Servers {
			if server.URL == "" {
				continue
			}
			if !allowName {
				server.Name = ""
			}
			servers = append(servers, server)
		}
		if len(servers) > 0 {
			return servers
		}
	}
	if cfg.ServerURL != "" {
		return []Server{{URL: cfg.ServerURL}}
	}
	return nil
}

// buildComponents merges the user-provided Components with the configured
// SecuritySchemes without mutating either input.
func buildComponents(cfg *Config) map[string]any {
	if len(cfg.Components) == 0 && len(cfg.SecuritySchemes) == 0 {
		return nil
	}

	components := make(map[string]any, len(cfg.Components)+1)
	maps.Copy(components, cfg.Components)

	if len(cfg.SecuritySchemes) > 0 {
		// Preserve any securitySchemes the user already placed in Components by
		// merging rather than overwriting.
		schemes := make(map[string]any, len(cfg.SecuritySchemes))
		if existing, ok := components["securitySchemes"].(map[string]any); ok {
			maps.Copy(schemes, existing)
		}
		maps.Copy(schemes, cfg.SecuritySchemes)
		components["securitySchemes"] = schemes
	}

	return components
}

// dropQuerystringParameters filters out parameters using the OpenAPI 3.2-only
// "querystring" location, returning the input slice unchanged when none match.
func dropQuerystringParameters(extras []fiber.RouteParameter) []fiber.RouteParameter {
	isQuerystring := func(in string) bool {
		return utils.EqualFold(utils.TrimSpace(in), paramLocationQuerystring)
	}
	for i := range extras {
		if !isQuerystring(extras[i].In) {
			continue
		}
		filtered := append([]fiber.RouteParameter(nil), extras[:i]...)
		for j := i + 1; j < len(extras); j++ {
			if isQuerystring(extras[j].In) {
				continue
			}
			filtered = append(filtered, extras[j])
		}
		return filtered
	}
	return extras
}

func mergeRouteParameters(params []parameter, index map[string]int, extras []fiber.RouteParameter) []parameter {
	if len(extras) == 0 {
		return params
	}
	for i := range extras {
		extra := &extras[i]
		if utils.TrimSpace(extra.Name) == "" {
			continue
		}
		location := utilsstrings.ToLower(utils.TrimSpace(extra.In))
		if location == "" {
			location = "query"
		}
		// OpenAPI spec: "example" and "examples" are mutually exclusive.
		// Prefer "examples" when both are provided.
		var paramExample any
		var paramExamples map[string]any
		if copiedExamples := maps.Clone(extra.Examples); len(copiedExamples) > 0 {
			paramExamples = copiedExamples
		} else {
			paramExample = extra.Example
		}
		param := parameter{
			Name:            extra.Name,
			In:              location,
			Description:     extra.Description,
			Required:        extra.Required,
			Example:         paramExample,
			Examples:        paramExamples,
			Deprecated:      extra.Deprecated,
			Style:           extra.Style,
			AllowEmptyValue: extra.AllowEmptyValue,
			AllowReserved:   extra.AllowReserved,
		}
		// A Parameter Object describes its value either with "schema" or with
		// "content", never both and never neither.
		switch content := routeMediaTypeContent(extra.Content); {
		case content != nil:
			param.Content = content
			// "example"/"examples" belong to the media type object when content
			// is used, so they are not repeated at the parameter level.
			param.Example = nil
			param.Examples = nil
		case location == paramLocationQuerystring:
			// The OpenAPI 3.2 "querystring" location must be described with
			// content, so wrap whatever schema was supplied into a single
			// entry rather than emitting a parameter with neither key.
			param.Content = map[string]map[string]any{
				querystringMediaType: contentEntry(
					schemaFrom(extra.Schema, extra.SchemaRef, schemaTypeString),
					"", paramExample, paramExamples,
				),
			}
			param.Example = nil
			param.Examples = nil
		default:
			param.Schema = schemaFrom(extra.Schema, extra.SchemaRef, schemaTypeString)
		}
		if extra.Explode != nil {
			explode := *extra.Explode
			param.Explode = &explode
		}
		if param.In == paramLocationPath {
			param.Required = true
		}
		params = appendOrReplaceParameter(params, index, &param)
	}
	return params
}

func appendOrReplaceParameter(params []parameter, index map[string]int, p *parameter) []parameter {
	if p == nil || p.Name == "" || p.In == "" {
		return params
	}
	key := p.In + ":" + p.Name
	if idx, ok := index[key]; ok {
		params[idx] = *p
		return params
	}
	index[key] = len(params)
	return append(params, *p)
}

func schemaFrom(schema map[string]any, schemaRef, defaultType string) map[string]any {
	if schemaRef != "" {
		return map[string]any{"$ref": schemaRef}
	}

	copied := maps.Clone(schema)
	if copied == nil {
		copied = map[string]any{}
	}
	if _, ok := copied[schemaKeyType]; !ok && defaultType != "" {
		copied[schemaKeyType] = defaultType
	}
	if len(copied) == 0 {
		return nil
	}
	return copied
}

func contentEntry(schema map[string]any, schemaRef string, example any, examples map[string]any) map[string]any {
	entry := map[string]any{}
	if schemaRef != "" {
		entry["schema"] = map[string]any{"$ref": schemaRef}
	} else if copied := maps.Clone(schema); len(copied) > 0 {
		entry["schema"] = copied
	}
	// OpenAPI spec: "example" and "examples" are mutually exclusive.
	// Prefer "examples" when both are provided.
	if ex := maps.Clone(examples); len(ex) > 0 {
		entry["examples"] = ex
	} else if example != nil {
		entry["example"] = example
	}
	return entry
}

// routeMediaTypeContent builds an OpenAPI content map from per-media-type
// entries, allowing a different schema/example/encoding per content type.
func routeMediaTypeContent(content map[string]fiber.RouteMediaType) map[string]map[string]any {
	if len(content) == 0 {
		return nil
	}
	out := make(map[string]map[string]any, len(content))
	for mediaType, mt := range content {
		if mediaType == "" {
			continue
		}
		entry := contentEntry(mt.Schema, mt.SchemaRef, mt.Example, mt.Examples)
		if enc := maps.Clone(mt.Encoding); len(enc) > 0 {
			entry["encoding"] = enc
		}
		if len(entry) == 0 {
			entry = map[string]any{}
		}
		out[mediaType] = entry
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// convertRouteResponses converts route response metadata, falling back to the
// route's Produces media type when a response documents a schema or example
// without naming any media type, so that data is not silently dropped.
func convertRouteResponses(routeResponses map[string]fiber.RouteResponse, fallbackMediaType string) map[string]response {
	var merged map[string]response
	if len(routeResponses) > 0 {
		merged = make(map[string]response, len(routeResponses))
		for code, resp := range routeResponses {
			content := routeMediaTypeContent(resp.Content)
			if content == nil {
				mediaTypes := resp.MediaTypes
				if len(mediaTypes) == 0 &&
					(len(resp.Schema) > 0 || resp.SchemaRef != "" || resp.Example != nil || len(resp.Examples) > 0) {
					// The response documents a schema or example but names no
					// media type. Emitting a description-only response would
					// silently discard what the author wrote, so fall back to
					// the route's Produces and to JSON when it has none.
					if fallbackMediaType != "" {
						mediaTypes = []string{fallbackMediaType}
					} else {
						mediaTypes = []string{fiber.MIMEApplicationJSON}
					}
				}
				content = mediaTypesToContent(mediaTypes, resp.Schema, resp.SchemaRef, resp.Example, resp.Examples)
			}
			merged[code] = response{
				Description: resp.Description,
				Content:     content,
				Headers:     maps.Clone(resp.Headers),
				Links:       maps.Clone(resp.Links),
			}
		}
	}
	return merged
}

// canonicalPathItem is the path template already published for a hierarchy,
// together with the parameter names it declares.
type canonicalPathItem struct {
	path   string
	params []string
}

// adoptCanonicalParamNames rewrites a variant's path parameter names to those
// of the canonical template it is being folded into. The two paths share a
// hierarchy — identical once template names are blanked — so their parameters
// correspond position by position.
func adoptCanonicalParamNames(variant *pathVariant, canonical []string) {
	if len(canonical) != len(variant.ParamNames) {
		// Defensive: a hierarchy match implies equal counts, so this cannot
		// normally happen. Renaming on a mismatch would be worse than leaving
		// the names alone.
		return
	}

	renamed := make(map[string]string, len(canonical))
	for i, old := range variant.ParamNames {
		renamed[old] = canonical[i]
	}

	if len(variant.ParamConstraints) > 0 {
		constraints := make(map[string]string, len(variant.ParamConstraints))
		for name, raw := range variant.ParamConstraints {
			if newName, ok := renamed[name]; ok {
				name = newName
			}
			constraints[name] = raw
		}
		variant.ParamConstraints = constraints
	}

	// Aliases map the author's route-pattern names onto emitted names, so they
	// have to point at the canonical names for AddParameter(in: "path") to keep
	// matching after the move.
	if len(variant.PathParamAliases) > 0 {
		aliases := make(map[string]string, len(variant.PathParamAliases))
		for raw, emitted := range variant.PathParamAliases {
			if newName, ok := renamed[emitted]; ok {
				emitted = newName
			}
			aliases[raw] = emitted
		}
		variant.PathParamAliases = aliases
	}

	variant.ParamNames = append([]string(nil), canonical...)
}

func remapRouteParameters(extras []fiber.RouteParameter, aliases map[string]string, pathParams []string) []fiber.RouteParameter {
	if len(extras) == 0 {
		return nil
	}
	pathSet := make(map[string]struct{}, len(pathParams))
	for _, name := range pathParams {
		pathSet[name] = struct{}{}
	}
	out := make([]fiber.RouteParameter, 0, len(extras))
	for i := range extras {
		copyExtra := extras[i]
		if utils.EqualFold(utils.TrimSpace(copyExtra.In), paramLocationPath) {
			if mapped, ok := aliases[copyExtra.Name]; ok {
				copyExtra.Name = mapped
			}
			if _, ok := pathSet[copyExtra.Name]; !ok {
				continue
			}
		}
		out = append(out, copyExtra)
	}
	return out
}

func mediaTypesToContent(mediaTypes []string, schema map[string]any, schemaRef string, example any, examples map[string]any) map[string]map[string]any {
	if len(mediaTypes) == 0 {
		return nil
	}
	content := make(map[string]map[string]any, len(mediaTypes))
	for _, mediaType := range mediaTypes {
		if mediaType == "" {
			continue
		}
		entry := contentEntry(schema, schemaRef, example, examples)
		if len(entry) == 0 {
			entry = map[string]any{}
		}
		content[mediaType] = entry
	}
	if len(content) == 0 {
		return nil
	}
	return content
}

func buildRequestBody(routeBody *fiber.RouteRequestBody) *requestBody {
	if routeBody == nil {
		return nil
	}
	content := routeMediaTypeContent(routeBody.Content)
	if content == nil {
		content = mediaTypesToContent(routeBody.MediaTypes, routeBody.Schema, routeBody.SchemaRef, routeBody.Example, routeBody.Examples)
	}
	merged := &requestBody{
		Description: routeBody.Description,
		Required:    routeBody.Required,
		Content:     content,
	}
	// Omit requestBody entirely when content could not be built, as the
	// OpenAPI specification requires at least one media type in content.
	if len(merged.Content) == 0 {
		return nil
	}
	return merged
}

// shouldIncludeRequestBody reports whether an implicit request body should be
// added for a route without explicit request body metadata: only when the route
// explicitly declared a request media type via Consumes. The GET/HEAD/TRACE
// strip in generateSpec is the single authority on which methods may carry a
// body.
func shouldIncludeRequestBody(reqType string, route *fiber.Route) bool {
	return reqType != "" && route != nil
}

func defaultResponseForMethod(method, mediaType string) (string, response) {
	status := "200"
	description := "OK"

	switch method {
	case fiber.MethodDelete, fiber.MethodHead:
		status = "204"
		description = "No Content"
	default:
		// Keep default 200/OK status
	}

	resp := response{Description: description}
	if mediaType != "" && status != "204" {
		resp.Content = map[string]map[string]any{
			mediaType: {},
		}
	}
	return status, resp
}

// pathState carries the in-progress OpenAPI path while walking a Fiber route
// pattern; optional parameters fork the walk into include/exclude branches.
type pathState struct {
	aliases map[string]string
	// constraints maps an emitted parameter name to the raw text of its
	// "<...>" span, which types the generated schema.
	constraints map[string]string
	path        string
	params      []string
	paramIdx    int
}

func (s pathState) clone() pathState {
	return pathState{
		path:        s.path,
		params:      append([]string(nil), s.params...),
		aliases:     maps.Clone(s.aliases),
		constraints: maps.Clone(s.constraints),
		paramIdx:    s.paramIdx,
	}
}

func buildOpenAPIPathVariants(fiberPath string, params []string) []pathVariant {
	var (
		length   = len(fiberPath)
		variants []pathVariant
	)

	var walk func(i int, current pathState)
	walk = func(i int, current pathState) {
		for i < length {
			switch fiberPath[i] {
			case ':':
				tokenStart := i + 1
				i = tokenStart
				for i < length {
					c := fiberPath[i]
					// '<' opens a constraint; the rest mirrors path.go's
					// parameterEndChars, including ':' and '\\' — omitting
					// those silently swallowed a following parameter.
					if c == '<' || c == '?' || c == '/' || c == '-' || c == '.' || c == ':' || c == '\\' {
						break
					}
					i++
				}
				tokenName := fiberPath[tokenStart:i]

				var rawConstraints string
				if i < length && fiberPath[i] == '<' {
					rawConstraints, i = scanConstraintSpan(fiberPath, i)
				}

				isOptional := i < length && fiberPath[i] == '?'
				if isOptional {
					i++
				}

				resolved := resolveOpenAPIPathParamName(current.paramIdx, tokenName, params)
				includeState := current.clone()
				name := uniquePathParamName(resolved.openAPI, includeState.params)
				includeState.path += "{" + name + "}"
				includeState.params = append(includeState.params, name)
				includeState.aliases[resolved.raw] = name
				if tokenName != "" {
					includeState.aliases[tokenName] = name
				}
				if rawConstraints != "" {
					if includeState.constraints == nil {
						includeState.constraints = make(map[string]string, 1)
					}
					includeState.constraints[name] = rawConstraints
				}
				includeState.paramIdx++

				if isOptional {
					excludeState := current.clone()
					excludeState.paramIdx++
					walk(i, includeState)
					// Each optional parameter doubles the walk, so a route with
					// many of them would otherwise build 2^n variants (and
					// gigabytes) inside a request. Stop forking once the cap is
					// reached; the fully-populated variant is always emitted.
					if len(variants) < maxPathVariants {
						walk(i, excludeState)
					}
					return
				}
				current = includeState

			case '*', '+':
				resolved := resolveOpenAPIWildcardParamName(current.paramIdx, params)
				name := uniquePathParamName(resolved.openAPI, current.params)
				current.path += "{" + name + "}"
				current.params = append(current.params, name)
				current.aliases[resolved.raw] = name
				current.paramIdx++
				i++

			case '\\':
				// The route grammar escapes the next character, matching it
				// literally (see path.go escapeChar).
				if i+1 < length {
					// Slice the byte; string(byte) would re-encode it as a
					// code point and corrupt multi-byte UTF-8.
					current.path += fiberPath[i+1 : i+2]
				}
				i += 2

			default:
				// Append the whole literal run at once instead of one byte at a
				// time.
				runStart := i
				for i < length {
					c := fiberPath[i]
					if c == ':' || c == '*' || c == '+' || c == '\\' {
						break
					}
					i++
				}
				current.path += fiberPath[runStart:i]
			}
		}

		finalPath := current.path
		if finalPath == "" {
			finalPath = "/"
		}
		variants = append(variants, pathVariant{
			Path:             finalPath,
			ParamNames:       append([]string(nil), current.params...),
			PathParamAliases: current.aliases,
			ParamConstraints: current.constraints,
		})
	}

	walk(0, pathState{
		path:     "",
		params:   nil,
		aliases:  map[string]string{},
		paramIdx: 0,
	})

	seen := make(map[string]struct{}, len(variants))
	unique := make([]pathVariant, 0, len(variants))
	for _, variant := range variants {
		path := variant.Path
		for len(path) > 1 && strings.HasSuffix(path, "/") {
			path = path[:len(path)-1]
		}
		// An interior empty segment means a mid-path optional parameter was
		// omitted. The router only matches that with a literal empty segment
		// ("/api//users/1", never "/api/users/1"), so publishing either form
		// would document an endpoint that does not exist.
		if strings.Contains(path, "//") {
			continue
		}
		variant.Path = path

		key := variant.Path + "|" + strings.Join(variant.ParamNames, ",")
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		unique = append(unique, variant)
	}

	return unique
}

// uniquePathParamName appends a numeric suffix when name is already used in
// this path variant: OpenAPI path templates must not repeat parameter names,
// but distinct Fiber parameters can sanitize to the same identifier.
func uniquePathParamName(name string, used []string) string {
	candidate := name
	for i := 2; slices.Contains(used, candidate); i++ {
		candidate = fmt.Sprintf("%s_%d", name, i)
	}
	return candidate
}

func resolveOpenAPIPathParamName(paramIdx int, extracted string, params []string) resolvedParamName {
	raw := extracted
	if paramIdx < len(params) && params[paramIdx] != "" {
		raw = params[paramIdx]
	}
	if raw == "" {
		raw = extracted
	}
	return resolvedParamName{
		raw:     raw,
		openAPI: sanitizeOpenAPIParamName(raw, paramIdx+1),
	}
}

func resolveOpenAPIWildcardParamName(paramIdx int, params []string) resolvedParamName {
	raw := wildcardParamName
	if paramIdx < len(params) && params[paramIdx] != "" {
		raw = params[paramIdx]
	}
	return resolvedParamName{
		raw:     raw,
		openAPI: sanitizeOpenAPIWildcardParamName(raw, paramIdx+1),
	}
}

func sanitizeOpenAPIWildcardParamName(name string, idx int) string {
	trimmed := strings.TrimLeft(name, "*+")
	if trimmed == "" {
		trimmed = wildcardParamName
	}
	trimmed = strings.TrimLeft(trimmed, "_.-")
	if trimmed == "" {
		trimmed = wildcardParamName
	}
	if trimmed[0] >= '0' && trimmed[0] <= '9' {
		trimmed = wildcardParamName + trimmed
	}
	if !strings.HasPrefix(trimmed, wildcardParamName) {
		trimmed = wildcardParamName + trimmed
	}
	return sanitizeOpenAPIParamName(trimmed, idx)
}

func sanitizeOpenAPIParamName(name string, idx int) string {
	trimmed := strings.TrimLeft(name, "*+")
	if trimmed == "" {
		trimmed = name
	}

	var builder strings.Builder
	builder.Grow(len(trimmed))
	for _, r := range trimmed {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '.' || r == '-' {
			_, _ = builder.WriteRune(r) //nolint:errcheck // strings.Builder.WriteRune never returns an error
			continue
		}
		_ = builder.WriteByte('_') //nolint:errcheck // strings.Builder.WriteByte never returns an error
	}
	sanitized := builder.String()
	if sanitized == "" {
		return fmt.Sprintf("param%d", idx)
	}
	return sanitized
}
