# v1.0.0. Created based on golangci-lint v1.54.2

run:
  timeout: 5m
  skip-dirs-use-default: false
  skip-dirs:
    - internal # TODO: Also run against internal dir
  modules-download-mode: readonly

output:
  sort-results: true

linters-settings:
  depguard:
    rules:
      all:
        deny:
          - pkg: "flag"
            desc: '`flag` package is only allowed in main.go'
          - pkg: "log"
            desc: 'logging is provided by `log`'
          - pkg: "io/ioutil"
            desc: '`io/ioutil` package is deprecated, use the `io` and `os` package instead'
          # TODO: Disallow reflect package
          # - pkg: "reflect"
          #   desc: '`reflect` package is dangerous to use'
          - pkg: "unsafe"
            desc: '`unsafe` package is dangerous to use'

  errcheck:
    check-type-assertions: true
    check-blank: true
    disable-default-exclusions: true

  errchkjson:
    report-no-exported: true

  exhaustive:
    check-generated: true
    default-signifies-exhaustive: true

  forbidigo:
    forbid:
      - ^(fmt\.Print(|f|ln)|print|println)$
      - 'http\.Default(Client|Transport)'
      # TODO: Eventually enable these patterns
      # - 'time\.Sleep'
      # - 'panic'
    analyze-types: true

  gci:
    sections:
      - standard
      - prefix(github.com/gofiber/fiber)
      - default
      - blank
      - dot
    custom-order: true

  goconst:
    numbers: true

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - hugeParam
      - rangeValCopy
    settings:
      captLocal:
        paramsOnly: false
      elseif:
        skipBalanced: false
      underef:
        skipRecvDeref: false
      unnamedResult:
        checkExported: true

  gofumpt:
    module-path: github.com/gofiber/fiber
    extra-rules: true

  gosec:
    config:
      global:
        show-ignored: true
        audit: true

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  grouper:
    import-require-single-import: true
    import-require-grouping: true

  loggercheck:
    require-string-key: true
    no-printf-like: true

  misspell:
    locale: US

  nolintlint:
    require-explanation: true
    require-specific: true

  nonamedreturns:
    report-error-in-defer: true

  predeclared:
    q: true

  promlinter:
    strict: true

  reassign:
    patterns:
      - '.*'

  revive:
    enable-all-rules: true
    rules:
      # Provided by gomnd linter
      - name: add-constant
        disabled: true
      - name: argument-limit
        disabled: true
      # Provided by bidichk
      - name: banned-characters
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: comment-spacings
        arguments:
          - nolint
          - msgp
      - name: cyclomatic
        disabled: true
      - name: exported
        disabled: true
      - name: file-header
        disabled: true
      - name: function-result-limit
        arguments: [3]
      - name: function-length
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: nested-structs
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: modifies-parameter
        disabled: true
      - name: package-comments
        disabled: true
      - name: use-any
        disabled: true # TODO: Enable once we drop support for Go 1.17

  stylecheck:
    checks:
      - all
      - -ST1000
      - -ST1020
      - -ST1021
      - -ST1022

  tagalign:
    strict: true

  tagliatelle:
    case:
      rules:
        json: snake

  tenv:
    all: true

  testpackage:
    skip-regexp: "^$"

  # unparam:
  #   check-exported: true

  usestdlibvars:
    http-method: true
    http-status-code: true
    time-weekday: true
    time-month: true
    # time-layout: true
    crypto-hash: true
    default-rpc-path: true
    os-dev-null: true
    sql-isolation-level: true
    tls-signature-scheme: true
    constant-kind: true
    syslog-priority: true

  wrapcheck:
    ignorePackageGlobs:
      - github.com/gofiber/fiber/*
      - github.com/valyala/fasthttp

issues:
  exclude-use-default: false
  exclude-case-sensitive: true
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
      - goerr113
      text: 'do not define dynamic errors, use wrapped static errors instead*'
  # fix: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    # - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    # - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    # - exhaustivestruct
    # - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    # - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals # TODO: Eventually enable this again
    # - gochecknoinits # TODO: Eventually enable this again
    # - gocognit
    - goconst
    - gocritic
    # - gocyclo
    # - godot
    # - godox
    - goerr113
    - gofmt
    - gofumpt
    # - goheader
    # - goimports
    # - golint
    # - gomnd # TODO: Eventually enable this again
    - gomoddirectives
    # - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - ifshort
    # - importas
    - ineffassign
    # - interfacebloat
    # - interfacer
    # - ireturn
    # - lll
    - loggercheck
    # - maintidx
    - makezero
    # - maligned
    - mirror
    - misspell
    - musttag
    - nakedret
    # - nestif
    - nilerr
    - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosnakecase
    - nosprintfhostport
    - paralleltest
    # - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    # - testpackage # TODO: Enable once https://github.com/gofiber/fiber/issues/2252 is implemented
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varcheck
    # - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    # - wsl
    - zerologlint
