// Code generated by ifacemaker; DO NOT EDIT.

package fiber

import (
	"bufio"
	"context"
	"crypto/tls"
	"io"
	"mime/multipart"
	"net"
	"time"

	"github.com/valyala/fasthttp"
)

// Ctx represents the Context which hold the HTTP request and response.
// It has methods for the request query string, parameters, body, HTTP headers and so on.
type Ctx interface {
	// App returns the *App reference to the instance of the Fiber application
	App() *App
	// BaseURL returns (protocol + host + base path).
	BaseURL() string
	// RequestCtx returns *fasthttp.RequestCtx that carries a deadline
	// a cancellation signal, and other values across API boundaries.
	RequestCtx() *fasthttp.RequestCtx
	// Context returns a context implementation that was set by
	// user earlier or returns a non-nil, empty context, if it was not set earlier.
	Context() context.Context
	// SetContext sets a context implementation by user.
	SetContext(ctx context.Context)
	// Copy returns a detached snapshot of the context that stays valid after the
	// handler returns.
	//
	// A live Ctx is pooled and its request buffers are handed to the next request
	// on the connection, so reading one from a goroutine that outlives the handler
	// returns whatever arrived next. Copy deep-copies the request, the path buffers
	// and the route parameters into a context that is never pooled, so the goroutine
	// sees the request the handler saw. Locals come across as they are: the entries
	// are copied, the values in them are shared.
	//
	// A request body that is still a stream is not copied; read it, or call Body, on
	// the original first. The copy is for reading otherwise: its response is a
	// detached buffer that never reaches the client, and it is always a *DefaultCtx
	// even under a custom Ctx, so writing to it, or driving the chain again with
	// Next or RestartRouting, changes nothing the client will see. It does not
	// observe the request's cancellation either; when the goroutine needs that, take
	// Context() from the original before the handler returns.
	Copy() Ctx
	// Deadline returns the time when work done on behalf of this context
	// should be canceled. Ctx carries no deadline, so ok is always false.
	//
	// Ctx satisfies context.Context as a context that can never be canceled: it is
	// pooled and reused, so it cannot honor the stability and concurrency the
	// interface requires. Pass Context() to anything that is cancellation-aware or
	// that outlives the handler.
	Deadline() (time.Time, bool)
	// Done returns a channel that's closed when work done on behalf of this
	// context should be canceled. Ctx can never be canceled, so Done always
	// returns nil, which context.Context explicitly permits. See Deadline.
	Done() <-chan struct{}
	// Err returns nil until the Done channel is closed. Done is always nil here,
	// so Err always returns nil. See Deadline.
	Err() error
	// Request return the *fasthttp.Request object
	// This allows you to use all fasthttp request methods
	// https://godoc.org/github.com/valyala/fasthttp#Request
	// Returns nil if the context has been released.
	Request() *fasthttp.Request
	// Response return the *fasthttp.Response object
	// This allows you to use all fasthttp response methods
	// https://godoc.org/github.com/valyala/fasthttp#Response
	// Returns nil if the context has been released.
	Response() *fasthttp.Response
	// Body returns the request body, decompressing it when the request declares a
	// Content-Encoding the app accepts.
	//
	// Req and Res both carry a Body, so on Ctx the request wins, as it does for
	// Get. Use Res().Body() for what the handler has written so far.
	Body() []byte
	// ContentLength returns the value of the Content-Length request header.
	//
	// Req and Res both carry a ContentLength, so on Ctx the request wins, as it
	// does for Get. Use Res().ContentLength() for the length of the response.
	ContentLength() int
	// Cookies returns the value of the request cookie with the given key, or
	// defaultValue when the client did not send it.
	//
	// Req and Res both carry a Cookies, so on Ctx the request wins, as it does for
	// Get. Use Res().Cookies() for the cookies this response will set.
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting to use the value outside the Handler.
	Cookies(key string, defaultValue ...string) string
	// Get returns the HTTP request header specified by field.
	// Field names are case-insensitive
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting instead.
	Get(key string, defaultValue ...string) string
	// GetHeaders returns the HTTP request headers.
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting instead.
	GetHeaders() map[string][]string
	// GetReqHeaders returns the HTTP request headers.
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting instead.
	GetReqHeaders() map[string][]string
	// GetRespHeader returns the HTTP response header specified by field.
	// Field names are case-insensitive
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting instead.
	GetRespHeader(key string, defaultValue ...string) string
	// GetRespHeaders returns the HTTP response headers.
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting instead.
	GetRespHeaders() map[string][]string
	// ClientHelloInfo return CHI from context
	ClientHelloInfo() *tls.ClientHelloInfo
	// Next executes the next method in the stack that matches the current route.
	Next() error
	// RestartRouting instead of going to the next handler. This may be useful after
	// changing the request path. Note that handlers might be executed again.
	RestartRouting() error
	setHandlerCtx(ctx CustomCtx)
	// OriginalURL contains the original request URL.
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting to use the value outside the Handler.
	OriginalURL() string
	// RequestID returns the request identifier from the response header or request header.
	RequestID() string
	// Req returns a convenience type whose API is limited to operations
	// on the incoming request.
	Req() Req
	// Res returns a convenience type whose API is limited to operations
	// on the outgoing response.
	Res() Res
	// Redirect returns the Redirect reference.
	// Use Redirect().Status() to set custom redirection status code.
	// If status is not specified, status defaults to 303 See Other.
	// You can use Redirect().To(), Redirect().Route() and Redirect().Back() for redirection.
	Redirect() *Redirect
	// ViewBind Add vars to default view var map binding to template engine.
	// Variables are read by the Render method and may be overwritten.
	ViewBind(vars Map) error
	// Route returns the matched Route struct.
	Route() *Route
	// routeFallback builds the synthetic route for the fasthttp error handler.
	// Its Method field is resolved like c.Method() (including the raw-header
	// fallback for unregistered methods) so Route and Method always agree.
	// Never inlined: inlining it would push Route over the inlining budget.
	routeFallback() *Route
	// Endpoint returns the route that will handle this request, without advancing the
	// handler chain, so global middleware can read its Path or Name before calling
	// Next. Returns nil when no endpoint will run: 404, 405, and while the error
	// handler replays the chain for a request rejected at the protocol level.
	//
	// It looks ahead, where the neighboring accessors look back: Route reports the
	// route currently executing, which inside middleware is the middleware itself,
	// and Matched reports whether an endpoint has been selected yet.
	//
	// It scans the remaining routes in the request's tree bucket, so calling it from
	// global middleware costs a second router scan per request.
	Endpoint() *Route
	// FullPath returns the matched route path, including any group prefixes.
	FullPath() string
	// RouteName returns the name of the route currently executing, or an empty
	// string when the route is unnamed. Inside middleware this is the middleware's
	// own route; use Endpoint().Name to look ahead to the route that will handle
	// the request.
	RouteName() string
	// MountPath returns the prefix the sub-app owning the current route was mounted
	// under, or an empty string when the route belongs to the top-level app.
	//
	// Fiber mounts by cloning a sub-app's routes into the app that serves them with
	// the prefix already baked in, so Path inside a mounted handler is the whole
	// requested path, not one relative to the mount. MountPath is what tells such a
	// handler which prefix it is living under, to build links back into its own app
	// or to strip the prefix itself.
	//
	// It answers from the route that is running, unlike App.MountPath, which only
	// ever describes the app it is called on.
	MountPath() string
	// Matched returns true if the current request path was matched by the router.
	Matched() bool
	// IsMiddleware returns true if the current request handler was registered as middleware.
	IsMiddleware() bool
	// IsFinal returns true if the current request handler is the last one in the
	// chain, meaning nothing runs after it returns. It is the complement of
	// IsMiddleware, and false when no route matched at all.
	IsFinal() bool
	// OverrideParam overwrites a route parameter value by name.
	// If the parameter name does not exist in the route, this method does nothing.
	OverrideParam(name, value string)
	// SaveFile saves any multipart file to disk.
	SaveFile(fileheader *multipart.FileHeader, path string) error
	// SaveFileToStorage saves any multipart file to an external storage system.
	SaveFileToStorage(fileheader *multipart.FileHeader, path string, storage Storage) error
	// Error returns an *Error carrying the given status code, so a handler can
	// reject a request in one line:
	//
	//	return c.Error(fiber.StatusBadRequest, "id must be numeric")
	//
	// The message defaults to the status text when omitted. Returning the error
	// hands it to the app's ErrorHandler, which is what writes the response; Error
	// itself sets nothing on the response.
	Error(status int, message ...string) error
	// Status sets the HTTP status for the response.
	// This method is chainable.
	Status(status int) Ctx
	// ID returns the connection-unique identifier fasthttp assigned to this
	// request. It is cheap and always present, unlike RequestID, which reads a
	// header a client or proxy has to have set. It is not unique across processes
	// or restarts, so it is for correlating log lines within one server run.
	ID() uint64
	// StartTime returns the time the server began handling this request. It is the
	// reference point Elapsed measures from.
	StartTime() time.Time
	// Elapsed returns how long this request has been handled so far, measured from
	// StartTime. Called after the handler chain has run, it is the request latency.
	Elapsed() time.Duration
	// LocalAddr returns the server-side address of the connection this request
	// arrived on. IP returns the client address as a string; this is the full
	// net.Addr, so the port, network, and unix socket path survive.
	LocalAddr() net.Addr
	// RemoteAddr returns the address of the immediate peer, which is the proxy
	// rather than the client when the app sits behind one. Use IP or IPs for the
	// client address a trusted proxy forwarded.
	RemoteAddr() net.Addr
	// Hijack registers a handler that takes over the connection once the current
	// response is sent, for protocols Fiber does not speak itself. The handler runs
	// on the connection's own goroutine, after which the connection is closed
	// unless the server has KeepHijackedConns set.
	//
	// The Ctx is pooled and reused, so the hijack handler must not touch it.
	Hijack(handler fasthttp.HijackHandler)
	// Hijacked returns true if Hijack has been called on this request, so a later
	// handler can tell that the connection is already spoken for and leave the
	// response alone.
	Hijacked() bool
	// String returns unique string representation of the ctx.
	//
	// The returned value may be useful for logging.
	String() string
	// Value makes it possible to retrieve values (Locals) under keys scoped to the request
	// and therefore available to all following routes that match the request. If the context
	// has been released and c.fasthttp is nil (for example, after ReleaseCtx), Value returns nil.
	Value(key any) any
	// configDependentPaths set paths for route recognition and prepared paths for the user,
	// here the features for caseSensitive, decoded paths, strict paths are evaluated
	configDependentPaths()
	// Reset is a method to reset context fields by given request when to use server handlers.
	Reset(fctx *fasthttp.RequestCtx)
	// release is a method to reset context fields when to use ReleaseCtx()
	release()
	// Abandon marks this context as abandoned. An abandoned context will not be
	// returned to the pool when ReleaseCtx is called.
	//
	// This is used by the timeout and SSE middlewares to return immediately while a
	// goroutine continues using the context safely.
	//
	// Only call ForceRelease after Abandon if you can guarantee no other goroutine
	// (including Fiber's requestHandler and ErrorHandler) will touch the context.
	// Callers that cannot make that guarantee themselves can instead call
	// ScheduleReclaim, which arranges a race-free ForceRelease once the handler has
	// finished and the request handler has released the context.
	Abandon()
	// IsAbandoned returns true if Abandon() was called on this context.
	IsAbandoned() bool
	// ForceRelease releases an abandoned context back to the pool.
	// This MUST only be called after all goroutines (including requestHandler and
	// ErrorHandler) have completely finished using this context. Calling it while
	// any goroutine is still running causes races.
	ForceRelease()
	// ScheduleReclaim arms automatic reclamation of an abandoned context, returning
	// it to the pool once it is safe to do so.
	//
	// handlerDone must be closed once the goroutine that still uses this context
	// (for the timeout middleware, the handler goroutine) has completely finished.
	// cancel, if non-nil, is the CancelFunc of the context installed for that
	// goroutine and is invoked as soon as it finishes.
	//
	// ForceRelease is performed only after BOTH handlerDone is closed AND the request
	// handler has released the context (signaled from ReleaseCtx/releaseDefaultCtx),
	// which makes the reclamation race-free. If handlerDone never closes — a handler
	// that never returns — the context is intentionally never reclaimed, because the
	// handler still owns it.
	//
	// This method calls Abandon internally, so callers do not need to call Abandon
	// separately. Calling Abandon before ScheduleReclaim is still safe (idempotent).
	ScheduleReclaim(handlerDone <-chan struct{}, cancel context.CancelFunc)
	// signalReleased records that the request handler is done touching an abandoned,
	// reclaim-armed context (event b). It is a no-op when reclamation was not armed
	// and is safe to call multiple times.
	signalReleased()
	renderExtensions(bind any)
	// Bind You can bind body, cookie, headers etc. into the map, map slice, struct easily by using Binding method.
	// It gives custom binding support, detailed binding options and more.
	// Replacement of: BodyParser, ParamsParser, GetReqHeaders, GetRespHeaders, AllParams, QueryParser, ReqHeaderParser
	Bind() *Bind
	// Methods to use with next stack.
	getMethodInt() int
	getIndexRoute() int
	getTreePathHash() int
	// pathSlashCount lazily counts the '/' bytes of the detection path and caches
	// the result for the request; matching uses it to reject route candidates
	// without walking their segments. app is the serving App, which can differ
	// from c.app when an App value was copied. When it registers no route that
	// consults the count, counting is skipped and 0 is returned — a real detection
	// path always contains a '/', so 0 doubles as the "unknown" state that makes
	// Route.match skip the quick-reject entirely.
	pathSlashCount(app *App) int
	getDetectionPath() string
	getValues() *[maxParams]string
	getMatched() bool
	getSkipNonUseRoutes() bool
	getFirstMatchIndex() int
	setIndexHandler(handler int)
	setIndexRoute(route int)
	setMatched(matched bool)
	setSkipNonUseRoutes(skip bool)
	setFirstMatchIndex(index int)
	setRoute(route *Route)
	getPathOriginal() string
	// Accepts checks if the specified extensions or content types are acceptable.
	Accepts(offers ...string) string
	// AcceptsCharsets checks if the specified charset is acceptable.
	AcceptsCharsets(offers ...string) string
	// AcceptsEncodings checks if the specified encoding is acceptable.
	AcceptsEncodings(offers ...string) string
	// AcceptsLanguages checks if the specified language is acceptable using
	// RFC 4647 Basic Filtering.
	AcceptsLanguages(offers ...string) string
	// AcceptsLanguagesExtended checks if the specified language is acceptable using
	// RFC 4647 Extended Filtering.
	AcceptsLanguagesExtended(offers ...string) string
	// BodyRaw contains the raw body submitted in a POST request.
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting instead.
	BodyRaw() []byte
	//nolint:nonamedreturns // gocritic unnamedResult prefers naming decoded body, decode count, and error
	tryDecodeBodyInOrder(originalBody *[]byte, encodings []string) (body []byte, decodesRealized uint8, err error)
	// BodyStream returns the request body as a stream.
	//
	// It is only non-nil when Config.StreamRequestBody is enabled and the body has
	// not already been buffered; IsBodyStream on the underlying request reports
	// which of the two is in play. Reading from the returned reader consumes the
	// body, so a later Body call will not see it.
	BodyStream() io.Reader
	// FullURL returns the full request URL (protocol + host + original URL).
	FullURL() string
	// UserAgent returns the User-Agent request header.
	UserAgent() string
	// Referer returns the Referer request header.
	Referer() string
	// Origin returns the Origin request header.
	Origin() string
	// AcceptLanguage returns the Accept-Language request header.
	// Repeated field lines are combined into one comma-joined list
	// (RFC 9110 Section 5.2), matching what AcceptsLanguages negotiates on.
	AcceptLanguage() string
	// AcceptEncoding returns the Accept-Encoding request header.
	// Repeated field lines are combined into one comma-joined list
	// (RFC 9110 Section 5.2), matching what AcceptsEncodings negotiates on.
	AcceptEncoding() string
	// HasHeader reports whether the request includes a header with the given key.
	HasHeader(key string) bool
	// MediaType returns the MIME type from the Content-Type header without parameters.
	MediaType() string
	// Charset returns the charset parameter from the Content-Type header.
	Charset() string
	// IsJSON reports whether the Content-Type header is JSON.
	IsJSON() bool
	// IsForm reports whether the Content-Type header is form-encoded.
	IsForm() bool
	// IsMultipart reports whether the Content-Type header is multipart form data.
	IsMultipart() bool
	// AcceptsJSON reports whether the Accept header allows JSON.
	AcceptsJSON() bool
	// AcceptsHTML reports whether the Accept header allows HTML.
	AcceptsHTML() bool
	// AcceptsXML reports whether the Accept header allows XML.
	AcceptsXML() bool
	// AcceptsEventStream reports whether the Accept header allows text/event-stream.
	AcceptsEventStream() bool
	// CookieNames returns the names of the cookies sent with the request, in the
	// order they appear in the Cookie header. A name repeated by the client is
	// returned once per occurrence.
	// Returned values are only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting to use the values outside the Handler.
	CookieNames() []string
	// AllCookies returns the cookies sent with the request as a name/value map.
	// When the client repeats a name the last value wins; use CookieNames to detect
	// that case.
	// Returned values are only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting to use the values outside the Handler.
	AllCookies() map[string]string
	// FormFile returns the first file by key from a MultipartForm.
	// The multipart form is parsed using the application's BodyLimit to prevent
	// unbounded memory usage.
	FormFile(key string) (*multipart.FileHeader, error)
	// FormValue returns the first value by key from a MultipartForm.
	// Search is performed in QueryArgs, PostArgs, MultipartForm and FormFile in this particular order.
	// Defaults to the empty string "" if the form value doesn't exist.
	// If a default value is given, it will return that value if the form value does not exist.
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting instead.
	// When the request is a multipart form, it is parsed using the application's
	// BodyLimit so the configured limit is consistently enforced.
	//
	// On a form request this lowercases the case-insensitive parts of the request's
	// own Content-Type, so a value obtained earlier from Get(HeaderContentType) —
	// which aliases those bytes unless Immutable is set — can change during the
	// call. Copy it first if you need it to outlive one.
	FormValue(key string, defaultValue ...string) string
	// Fresh returns true when the response is still “fresh” in the client's cache,
	// otherwise false is returned to indicate that the client cache is now stale
	// and the full response should be sent.
	// Freshness only applies to GET and HEAD requests; for any other method false is
	// returned, as RFC 9110 defines 304 Not Modified only for those methods and
	// requires If-Modified-Since to be ignored otherwise.
	// When a client sends the Cache-Control: no-cache request header to indicate an end-to-end
	// reload request, this module will return false to make handling these requests transparent.
	// https://github.com/jshttp/fresh/blob/master/index.js#L33
	Fresh() bool
	// IfNoneMatch returns the entity tags listed in the If-None-Match request
	// header. Repeated field lines are combined into one list (RFC 9110
	// Section 5.2), and a comma inside a quoted opaque-tag does not split it, so
	// `"v1,v2"` stays one tag. A wildcard header returns a single "*" element.
	// Tags are returned verbatim, weak "W/" prefix included, and are not validated.
	// Fresh already applies these tags to the response ETag; reach for this only to
	// implement a comparison of your own.
	IfNoneMatch() []string
	// IfModifiedSince returns the time carried by the If-Modified-Since request
	// header. It returns ErrHeaderNotFound when the header is absent, and a parse
	// error when the value is none of the three HTTP-date formats RFC 9110
	// Section 5.6.7 requires recipients to accept.
	IfModifiedSince() (time.Time, error)
	// GetAll returns every field line of the request header specified by key.
	// Field names are case-insensitive.
	//
	// A header repeated across field lines is semantically one comma-joined list
	// (RFC 9110 Section 5.2). GetAll keeps the lines apart so a caller can inspect
	// them individually, where Get returns only the first and GetHeaders builds a
	// map of the whole header block.
	// Returned values are only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting instead.
	GetAll(key string) []string
	// Authorization splits the Authorization request header into its auth-scheme
	// and the credentials that follow (RFC 9110 Section 11.6.2). Both are empty
	// when the header is absent. The credentials are returned verbatim — token68 or
	// auth-param list — and are neither decoded nor validated.
	Authorization() (scheme, credentials string)
	// Bearer returns the credentials of a Bearer Authorization header
	// (RFC 6750 Section 2.1), or an empty string when the header is absent or names
	// a different auth-scheme. The token is returned verbatim: it is not validated,
	// decoded, or verified, so it still has to be authenticated before it is trusted.
	Bearer() string
	// Host contains the host derived from the X-Forwarded-Host or Host HTTP header.
	// Returned value is only valid within the handler. Do not store any references.
	// In a network context, `Host` refers to the combination of a hostname and potentially a port number used for connecting,
	// while `Hostname` refers specifically to the name assigned to a device on a network, excluding any port information.
	// Example: URL: https://example.com:8080 -> Host: example.com:8080
	// Make copies or use the Immutable setting instead.
	// Please use Config.TrustProxy to prevent header spoofing if your app is behind a proxy.
	Host() string
	// Hostname contains the hostname derived from the X-Forwarded-Host or Host HTTP header using the c.Host() method.
	// Returned value is only valid within the handler. Do not store any references.
	// Example: URL: https://example.com:8080 -> Hostname: example.com
	// Make copies or use the Immutable setting instead.
	// Please use Config.TrustProxy to prevent header spoofing if your app is behind a proxy.
	Hostname() string
	// Port returns the remote port of the request.
	Port() string
	// IP returns the client's IP address. When the request comes from a trusted proxy (see
	// [TrustProxyConfig]), the value is extracted from the configured ProxyHeader by walking the
	// X-Forwarded-For chain right-to-left and skipping all trusted proxy IPs; the first
	// non-trusted IP in the chain is returned. Please use Config.TrustProxy to prevent header
	// spoofing if your app is behind a proxy.
	IP() string
	// extractIPsFromHeader will return a slice of IPs it found given a header name in the order they appear.
	// When IP validation is enabled, any invalid IPs will be omitted.
	extractIPsFromHeader(header string) []string
	// extractIPFromHeader returns the client IP from the given proxy header by walking the
	// X-Forwarded-For chain from right to left and stripping trusted proxy IPs. When trusted
	// proxies are configured, the rightmost non-trusted IP is returned; otherwise the first
	// valid IP (left-to-right) is returned. When IP validation is disabled, the raw header
	// value is returned as-is.
	extractIPFromHeader(header string) string
	// hasTrustedProxyConfig returns true if any trusted proxy configuration is set.
	hasTrustedProxyConfig() bool
	// isTrustedProxyIP checks whether the given IP string matches any configured trusted proxy.
	isTrustedProxyIP(ipStr string) bool
	// IPs returns a string slice of IP addresses specified in the X-Forwarded-For request header.
	// When IP validation is enabled, only valid IPs are returned.
	IPs() []string
	// Is returns the matching content type,
	// if the incoming request's Content-Type HTTP header field matches the MIME type specified by the type parameter
	Is(extension string) bool
	// HasBody returns true if the request declares a body via Content-Length, Transfer-Encoding, or already buffered payload data.
	HasBody() bool
	// IsWebSocket returns true if the request includes a WebSocket upgrade handshake.
	IsWebSocket() bool
	// IsPreflight returns true if the request is a CORS preflight.
	IsPreflight() bool
	// Secure returns whether a secure connection was established.
	Secure() bool
	// XHR returns a Boolean property, that is true, if the request's X-Requested-With header field is XMLHttpRequest,
	// indicating that the request was issued by a client library (such as jQuery).
	XHR() bool
	// Locals makes it possible to pass any values under keys scoped to the request
	// and therefore available to all following routes that match the request.
	//
	// All the values are removed from ctx after returning from the top
	// RequestHandler. Additionally, Close method is called on each value
	// implementing io.Closer before removing the value from ctx.
	Locals(key any, value ...any) any
	// Method returns the HTTP request method for the context, optionally overridden by the provided argument.
	// If no override is given or if the provided override is not a valid HTTP method, it returns the current method from the context.
	// Otherwise, it updates the context's method and returns the overridden method as a string.
	Method(override ...string) string
	// IsSafe reports whether the request method is safe, meaning it is not expected
	// to change server state (RFC 9110 Section 9.2.1).
	IsSafe() bool
	// IsIdempotent reports whether the request method is idempotent, meaning
	// repeating it has the same intended effect as making it once (RFC 9110
	// Section 9.2.2). Every safe method is also idempotent.
	IsIdempotent() bool
	// MultipartForm parse form entries from binary.
	// This returns a map[string][]string, so given a key, the value will be a string slice.
	//
	// On a form request this lowercases the case-insensitive parts of the request's
	// own Content-Type, so a value obtained earlier from Get(HeaderContentType) —
	// which aliases those bytes unless Immutable is set — can change during the
	// call. Copy it first if you need it to outlive one.
	MultipartForm() (*multipart.Form, error)
	// URI returns the parsed *fasthttp.URI of the request.
	// This allows you to use all fasthttp URI methods.
	// https://godoc.org/github.com/valyala/fasthttp#URI
	//
	// The returned value is owned by the request and is rewritten by a Path
	// override, so it is only valid within the handler. Do not store any references.
	URI() *fasthttp.URI
	// Path returns the path part of the request URL.
	// Optionally, you could override the path.
	// Make copies or use the Immutable setting to use the value outside the Handler.
	Path(override ...string) string
	// Params is used to get the route parameters.
	// Defaults to empty string "" if the param doesn't exist.
	// If a default value is given, it will return that value if the param doesn't exist.
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting to use the value outside the Handler.
	Params(key string, defaultValue ...string) string
	// Scheme contains the request protocol string: http or https for TLS requests.
	// Please use Config.TrustProxy to prevent header spoofing if your app is behind a proxy.
	Scheme() string
	// Protocol returns the HTTP protocol of request: HTTP/1.1 and HTTP/2.
	Protocol() string
	// Query returns the query string parameter in the url.
	// Defaults to empty string "" if the query doesn't exist.
	// If a default value is given, it will return that value if the query doesn't exist.
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting to use the value outside the Handler.
	Query(key string, defaultValue ...string) string
	// Queries returns a map of query parameters and their values.
	//
	// GET /?name=alex&wanna_cake=2&id=
	// Queries()["name"] == "alex"
	// Queries()["wanna_cake"] == "2"
	// Queries()["id"] == ""
	//
	// GET /?field1=value1&field1=value2&field2=value3
	// Queries()["field1"] == "value2"
	// Queries()["field2"] == "value3"
	//
	// GET /?list_a=1&list_a=2&list_a=3&list_b[]=1&list_b[]=2&list_b[]=3&list_c=1,2,3
	// Queries()["list_a"] == "3"
	// Queries()["list_b[]"] == "3"
	// Queries()["list_c"] == "1,2,3"
	//
	// GET /api/search?filters.author.name=John&filters.category.name=Technology&filters[customer][name]=Alice&filters[status]=pending
	// Queries()["filters.author.name"] == "John"
	// Queries()["filters.category.name"] == "Technology"
	// Queries()["filters[customer][name]"] == "Alice"
	// Queries()["filters[status]"] == "pending"
	Queries() map[string]string
	// Range returns a struct containing the type and a slice of ranges.
	Range(size int64) (Range, error)
	// Subdomains returns a slice of subdomains from the host, excluding the last `offset` components.
	// If the offset is negative or exceeds the number of subdomains, an empty slice is returned.
	// If the offset is zero every label (no trimming) is returned.
	Subdomains(offset ...int) []string
	// Stale returns the inverse of Fresh, indicating if the client's cached response is considered stale.
	Stale() bool
	// IsProxyTrusted checks trustworthiness of remote ip.
	// If Config.TrustProxy false, it returns false.
	// IsProxyTrusted can check remote ip by proxy ranges and ip map.
	IsProxyTrusted() bool
	// IsFromLocal will return true if request came from a loopback IP.
	IsFromLocal() bool
	// IsFromUnixSocket returns true if the request arrived over a Unix domain socket.
	IsFromUnixSocket() bool
	getBody() []byte
	// Append the specified value to the HTTP response header field.
	// If the header is not already set, it creates the header with the specified value.
	// Empty values are skipped: a sender must not generate empty list elements
	// (RFC 9110 Section 5.6.1.2).
	Append(field string, values ...string)
	// Add appends the given value to the response header field as a new field
	// line, leaving any existing lines untouched.
	//
	// This differs from Append, which folds values into a single comma-separated
	// line: headers whose values may themselves contain commas — Set-Cookie,
	// WWW-Authenticate, Link — have to be sent as separate lines to stay
	// unambiguous (RFC 9110 Section 5.3).
	Add(key, val string)
	// Attachment sets the HTTP response Content-Disposition header field to attachment.
	Attachment(filename ...string)
	// ClearCookie expires a specific cookie by key on the client side.
	// If no key is provided it expires all cookies that came with the request.
	ClearCookie(key ...string)
	// Cookie sets a cookie by passing a cookie struct.
	//
	// The argument is treated as read-only: the normalization this method applies
	// (default Path, SessionOnly, and the Secure implied by SameSite=None or
	// Partitioned) happens on a local copy, so a caller may reuse the same *Cookie
	// template across requests.
	Cookie(cookie *Cookie)
	// GetCookie reads back a cookie this response is already set to send, so a
	// later handler or middleware can inspect or re-emit what an earlier one wrote.
	// The second result is false when no cookie of that name has been set.
	//
	// The returned Cookie is a copy: changing it does not change the response.
	// Pass it to Cookie to write the change back.
	GetCookie(name string) (*Cookie, bool)
	// Download transfers the file from path as an attachment.
	// Typically, browsers will prompt the user for download.
	// By default, the Content-Disposition header filename= parameter is the filepath (this typically appears in the browser dialog).
	// Override this default with the filename parameter.
	Download(file string, filename ...string) error
	// Format performs content-negotiation on the Accept HTTP header.
	// It uses Accepts to select a proper format and calls the matching
	// user-provided handler function.
	// If no accepted format is found, and a format with MediaType "default" is given,
	// that default handler is called. If no format is found and no default is given,
	// StatusNotAcceptable is sent.
	Format(handlers ...ResFmt) error
	// AutoFormat performs content-negotiation on the Accept HTTP header.
	// It uses Accepts to select a proper format.
	// The supported content types are text/html, text/plain, application/json, application/xml, application/vnd.msgpack, and application/cbor.
	// When text/html is selected, the body is treated as plain text and HTML-escaped before being wrapped in a `<p>` element.
	// For more flexible content negotiation, use Format.
	// If the header is not specified or there is no proper format, text/plain is used.
	AutoFormat(body any) error
	// ContentType returns the Content-Type response header, parameters included.
	// It is the read side of Type, and of the content type Fiber sets for you when
	// a JSON, XML, or SendFile response goes out.
	//
	// When nothing has set one it reports fasthttp's default, "text/plain;
	// charset=utf-8", which is what would be sent — not an empty string.
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting instead.
	ContentType() string
	// Del removes every field line of the response header specified by key.
	// Field names are case-insensitive. Deleting a header that was never set is a
	// no-op.
	//
	// Del(HeaderSetCookie) withdraws every cookie this response was going to set,
	// which is not what ClearCookie does: ClearCookie adds a Set-Cookie that
	// expires the cookie already in the client's jar.
	Del(key string)
	// JSON converts any interface or string to JSON.
	// Array and slice values encode as JSON arrays,
	// except that []byte encodes as a base64-encoded string,
	// and a nil slice encodes as the null JSON value.
	// If the ctype parameter is given, this method will set the
	// Content-Type header equal to ctype. If ctype is not given,
	// The Content-Type header will be set to application/json; charset=utf-8.
	JSON(data any, ctype ...string) error
	// MsgPack converts any interface or string to MessagePack encoded bytes.
	// If the ctype parameter is given, this method will set the
	// Content-Type header equal to ctype. If ctype is not given,
	// The Content-Type header will be set to application/vnd.msgpack.
	MsgPack(data any, ctype ...string) error
	// CBOR converts any interface or string to CBOR encoded bytes.
	// If the ctype parameter is given, this method will set the
	// Content-Type header equal to ctype. If ctype is not given,
	// The Content-Type header will be set to application/cbor.
	CBOR(data any, ctype ...string) error
	// JSONP sends a JSON response with JSONP support.
	// This method is identical to JSON, except that it opts-in to JSONP callback support.
	// By default, the callback name is simply callback.
	//
	// The callback name is reduced to a JavaScript member expression: everything
	// outside [A-Za-z0-9_$.[]] is dropped. Callers routinely take the name straight
	// from the query string, which is what JSONP is for, and the name lands
	// verbatim in a same-origin text/javascript body — so an unfiltered one would
	// let a request supply arbitrary script for the app's own origin.
	JSONP(data any, callback ...string) error
	// XML converts any interface or string to XML.
	// This method also sets the content header to application/xml; charset=utf-8.
	XML(data any) error
	// Links joins the links followed by the property to populate the response's Link HTTP header field.
	Links(link ...string)
	// Location sets the response Location HTTP header to the specified path parameter.
	Location(path string)
	// getLocationFromRoute gets the URL location from a route using parameters.
	// Nil receivers and missing routes return ErrNotFound to match Route.URL semantics.
	getLocationFromRoute(route *Route, params Map) (string, error)
	// GetRouteURL generates URLs to named routes, with parameters. URLs are relative, for example: "/user/1831"
	GetRouteURL(routeName string, params Map) (string, error)
	// Render a template with data and sends a text/html response.
	// We support the following engines: https://github.com/gofiber/template
	Render(name string, bind any, layouts ...string) error
	// ResetBody discards the response body, keeping the status and headers.
	// Use it before replacing a partially written body — an error page over a
	// half-rendered view, a cached body over a fresh one.
	ResetBody()
	// Written reports whether anything has been written to the response body yet,
	// so middleware can tell a handler that produced a response from one that left
	// it untouched. A streamed body counts as written without draining the stream.
	//
	// Status and headers are not body writes: a handler that only called Status
	// leaves this false.
	Written() bool
	// Send sets the HTTP response body without copying it.
	// From this point onward the body argument must not be changed.
	Send(body []byte) error
	// SendEarlyHints allows the server to hint to the browser what resources a page would need
	// so the browser can preload them while waiting for the server's full response. Only Link
	// headers already written to the response will be transmitted as Early Hints.
	//
	// This is a HTTP/2+ feature but all browsers will either understand it or safely ignore it.
	//
	// NOTE: Older HTTP/1.1 non-browser clients may face compatibility issues.
	//
	// See: https://developer.chrome.com/docs/web-platform/early-hints and
	// https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Link#syntax
	SendEarlyHints(hints []string) error
	// SendFile transfers the file from the specified path.
	// By default, the file is not compressed. To enable compression, set SendFile.Compress to true.
	// The Content-Type response HTTP header field is set based on the file's extension.
	// If the file extension is missing or invalid, the Content-Type is detected from the file's format.
	SendFile(file string, config ...SendFile) error
	// NoContent replies 204 No Content: it sets the status, discards any body
	// already written, and drops the Content-Type a handler had set, since
	// RFC 9110 Section 6.4.1 gives a 204 no content to describe. fasthttp omits
	// Content-Type from a 204 on the wire either way; dropping it here keeps the
	// response consistent if something later moves it off 204.
	NoContent() error
	// SendStatus sets the HTTP status code and if the response body is empty,
	// it sets the correct status message in the body.
	SendStatus(status int) error
	// SendString sets the HTTP response body for string types.
	// This means no type assertion, recommended for faster performance
	SendString(body string) error
	// SendStream sets response body stream and optional body size.
	SendStream(stream io.Reader, size ...int) error
	// SendStreamWriter sets response body stream writer
	SendStreamWriter(streamWriter func(*bufio.Writer)) error
	// Set sets the response's HTTP header field to the specified key, value.
	Set(key, val string)
	setCanonical(key, val string)
	// StatusCode returns the status code currently set on the response. It is the
	// read side of Status, and reports 200 until something sets another code.
	//
	// Called after Next it is the status the chain settled on, which is what
	// logging, metrics, and caching middleware key off.
	StatusCode() int
	// Type sets the Content-Type HTTP header to the MIME type specified by the file extension.
	Type(extension string, charset ...string) Ctx
	// Vary adds the given header field to the Vary response header.
	// This will append the header, if not already listed; otherwise, leaves it listed in the current location.
	// Per RFC 9110 Section 12.5.5 the wildcard "*" only has meaning as the sole member of the field:
	// once "*" is added (or already present), the header is collapsed to a single "*".
	Vary(fields ...string)
	// Write appends p into response body.
	Write(p []byte) (int, error)
	// Writef appends f & a into response body writer.
	Writef(f string, a ...any) (int, error)
	// WriteString appends s to response body.
	WriteString(s string) (int, error)
	// Drop closes the underlying connection without sending any response headers or body.
	// This can be useful for silently terminating client connections, such as in DDoS mitigation
	// or when blocking access to sensitive endpoints.
	Drop() error
	// End immediately flushes the current response and closes the underlying connection.
	//
	// Note: End does not work when using streaming (e.g. fasthttp's HijackConn or SendStream),
	// because in streaming mode the connection is managed asynchronously and ctx.Conn() may return nil.
	End() error
}
