// Code generated by ifacemaker; DO NOT EDIT.

package fiber

// Req
type Req interface {
	Accepts(offers ...string) string
	AcceptsCharsets(offers ...string) string
	AcceptsEncodings(offers ...string) string
	AcceptsLanguages(offers ...string) string
	BaseURL() string
	Body() []byte
	Cookies(key string, defaultValue ...string) string
	Fresh() bool
	Get(key string, defaultValue ...string) string
	Host() string
	Hostname() string
	IP() string
	Is(extension string) bool
	IPs() []string
	Method() string
	OriginalURL() string
	Params(key string, defaultValue ...string) string
	Path() string
	Protocol() string
	Query(key string, defaultValue ...string) string
	Range(size int) (Range, error)
	Route() *Route
	Secure() bool
	Stale() bool
	Subdomains(offset ...int) []string
	XHR() bool
}
