// Code generated by ifacemaker; DO NOT EDIT.

package fiber

import (
	"bufio"
	"io"

	"github.com/valyala/fasthttp"
)

// Res is an interface for response-related Ctx methods.
type Res interface {
	// App returns the *App reference to the instance of the Fiber application
	App() *App
	// Append the specified value to the HTTP response header field.
	// If the header is not already set, it creates the header with the specified value.
	// Empty values are skipped: a sender must not generate empty list elements
	// (RFC 9110 Section 5.6.1.2).
	Append(field string, values ...string)
	// Add appends the given value to the response header field as a new field
	// line, leaving any existing lines untouched.
	//
	// This differs from Append, which folds values into a single comma-separated
	// line: headers whose values may themselves contain commas — Set-Cookie,
	// WWW-Authenticate, Link — have to be sent as separate lines to stay
	// unambiguous (RFC 9110 Section 5.3).
	//
	// The headers fasthttp stores in a slot of their own cannot repeat, and Add
	// does not append for them: Content-Type, Content-Encoding, Content-Length,
	// Connection, Server and Trailer are replaced, and Transfer-Encoding and Date
	// are ignored because fasthttp writes them itself. Use Set for those.
	Add(key, val string)
	// Attachment sets the HTTP response Content-Disposition header field to attachment.
	Attachment(filename ...string)
	// ClearCookie expires a specific cookie by key on the client side.
	// If no key is provided it expires all cookies that came with the request.
	ClearCookie(key ...string)
	// RequestCtx returns *fasthttp.RequestCtx that carries a deadline
	// a cancellation signal, and other values across API boundaries.
	RequestCtx() *fasthttp.RequestCtx
	// Cookie sets a cookie by passing a cookie struct.
	//
	// The argument is treated as read-only: the normalization this method applies
	// (default Path, SessionOnly, and the Secure implied by SameSite=None or
	// Partitioned) happens on a local copy, so a caller may reuse the same *Cookie
	// template across requests.
	Cookie(cookie *Cookie)
	// GetCookie reads back a cookie this response is already set to send, so a
	// later handler or middleware can inspect or re-emit what an earlier one wrote.
	// The second result is false when no cookie of that name has been set, or when
	// its Set-Cookie field value does not parse.
	//
	// Cookie names are case-sensitive (RFC 6265 Section 4.1.1). A name written more
	// than once resolves to the first occurrence; use Cookies to see them all.
	//
	// The returned Cookie is a copy: changing it does not change the response.
	// Pass it to Cookie to write the change back.
	GetCookie(name string) (*Cookie, bool)
	// Cookies returns a copy of every cookie this response is set to send, in the
	// order they were added. It returns nil when none have been set.
	//
	// Repeated names are kept apart, so a response that sets one name at two paths
	// yields both. A Set-Cookie whose field value does not parse is skipped.
	//
	// These are the response's own Set-Cookie headers. For the cookies the client
	// sent, use Req.Cookies or Req.AllCookies.
	Cookies() []*Cookie
	// Download transfers the file from path as an attachment.
	// Typically, browsers will prompt the user for download.
	// By default, the Content-Disposition header filename= parameter is the filepath (this typically appears in the browser dialog).
	// Override this default with the filename parameter.
	Download(file string, filename ...string) error
	// Response return the *fasthttp.Response object
	// This allows you to use all fasthttp response methods
	// https://godoc.org/github.com/valyala/fasthttp#Response
	Response() *fasthttp.Response
	// Format performs content-negotiation on the Accept HTTP header.
	// It uses Accepts to select a proper format and calls the matching
	// user-provided handler function.
	// If no accepted format is found, and a format with MediaType "default" is given,
	// that default handler is called. If no format is found and no default is given,
	// StatusNotAcceptable is sent.
	Format(handlers ...ResFmt) error
	// AutoFormat performs content-negotiation on the Accept HTTP header.
	// It uses Accepts to select a proper format.
	// The supported content types are text/html, text/plain, application/json, application/xml, application/vnd.msgpack, and application/cbor.
	// When text/html is selected, the body is treated as plain text and HTML-escaped before being wrapped in a `<p>` element.
	// For more flexible content negotiation, use Format.
	// If the header is not specified or there is no proper format, text/plain is used.
	AutoFormat(body any) error
	// ContentLength returns the value of the Content-Length response header.
	//
	// It reports what the header declares, not what has been buffered: fasthttp
	// fills Content-Length in as it serializes the response, so inside a handler
	// this is 0 unless something set it explicitly, and -1 once the body is a
	// stream of unknown length. Use len(Res.Body()) for the bytes buffered so far.
	ContentLength() int
	// ContentType returns the Content-Type response header, parameters included.
	// It is the read side of Type, and of the content type Fiber sets for you when
	// a JSON, XML, or SendFile response goes out.
	//
	// When nothing has set one it reports what would be sent: fasthttp's default,
	// "text/plain; charset=utf-8", or an empty string under
	// Config.DisableDefaultContentType.
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting instead.
	ContentType() string
	// Del removes every field line of the response header specified by key.
	// Field names are case-insensitive. Deleting a header that was never set is a
	// no-op.
	//
	// Del(HeaderSetCookie) withdraws every cookie this response was going to set,
	// which is not what ClearCookie does: ClearCookie adds a Set-Cookie that
	// expires the cookie already in the client's jar.
	Del(key string)
	// Get (a.k.a. GetRespHeader) returns the HTTP response header specified by field.
	// Field names are case-insensitive
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting instead.
	Get(key string, defaultValue ...string) string
	// GetHeaders (a.k.a GetRespHeaders) returns the HTTP response headers.
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting instead.
	GetHeaders() map[string][]string
	// JSON converts any interface or string to JSON.
	// Array and slice values encode as JSON arrays,
	// except that []byte encodes as a base64-encoded string,
	// and a nil slice encodes as the null JSON value.
	// If the ctype parameter is given, this method will set the
	// Content-Type header equal to ctype. If ctype is not given,
	// The Content-Type header will be set to application/json; charset=utf-8.
	JSON(data any, ctype ...string) error
	// MsgPack converts any interface or string to MessagePack encoded bytes.
	// If the ctype parameter is given, this method will set the
	// Content-Type header equal to ctype. If ctype is not given,
	// The Content-Type header will be set to application/vnd.msgpack.
	MsgPack(data any, ctype ...string) error
	// CBOR converts any interface or string to CBOR encoded bytes.
	// If the ctype parameter is given, this method will set the
	// Content-Type header equal to ctype. If ctype is not given,
	// The Content-Type header will be set to application/cbor.
	CBOR(data any, ctype ...string) error
	// JSONP sends a JSON response with JSONP support.
	// This method is identical to JSON, except that it opts-in to JSONP callback support.
	// By default, the callback name is simply callback.
	//
	// The callback name is reduced to a JavaScript member expression: everything
	// outside [A-Za-z0-9_$.[]] is dropped. Callers routinely take the name straight
	// from the query string, which is what JSONP is for, and the name lands
	// verbatim in a same-origin text/javascript body — so an unfiltered one would
	// let a request supply arbitrary script for the app's own origin.
	JSONP(data any, callback ...string) error
	// XML converts any interface or string to XML.
	// This method also sets the content header to application/xml; charset=utf-8.
	XML(data any) error
	// Links joins the links followed by the property to populate the response's Link HTTP header field.
	Links(link ...string)
	// Location sets the response Location HTTP header to the specified path parameter.
	Location(path string)
	// OriginalURL contains the original request URL.
	// Returned value is only valid within the handler. Do not store any references.
	// Make copies or use the Immutable setting to use the value outside the Handler.
	OriginalURL() string
	// Redirect returns the Redirect reference.
	// Use Redirect().Status() to set custom redirection status code.
	// If status is not specified, status defaults to 303 See Other.
	// You can use Redirect().To(), Redirect().Route() and Redirect().Back() for redirection.
	Redirect() *Redirect
	// ViewBind Add vars to default view var map binding to template engine.
	// Variables are read by the Render method and may be overwritten.
	ViewBind(vars Map) error
	// getLocationFromRoute gets the URL location from a route using parameters.
	// Nil receivers and missing routes return ErrNotFound to match Route.URL semantics.
	getLocationFromRoute(route *Route, params Map) (string, error)
	// GetRouteURL generates URLs to named routes, with parameters. URLs are relative, for example: "/user/1831"
	GetRouteURL(routeName string, params Map) (string, error)
	// Render a template with data and sends a text/html response.
	// We support the following engines: https://github.com/gofiber/template
	Render(name string, bind any, layouts ...string) error
	renderExtensions(bind any)
	// Body returns the response body buffered so far, which lets middleware
	// inspect or checksum what a handler produced before it is written out.
	//
	// A streamed body returns nil rather than being drained. Reading it would pull
	// the whole stream into memory and turn the response into a buffered one, which
	// would hang an SSE route and defeat a large SendFile; use Written to tell a
	// streaming response from one that produced nothing, and the underlying
	// Response.Body if you really do want to materialize the stream.
	//
	// Returned value is only valid within the handler and is invalidated by the
	// next write to the response. Do not store any references; copy it instead.
	Body() []byte
	// ResetBody discards the response body, keeping the status and headers.
	// Use it before replacing a partially written body — an error page over a
	// half-rendered view, a cached body over a fresh one.
	ResetBody()
	// Written reports whether anything has been written to the response body yet,
	// so middleware can tell a handler that produced a response from one that left
	// it untouched. A streamed body counts as written without draining the stream,
	// which is the case Body deliberately answers nil for.
	//
	// Status and headers are not body writes: a handler that only called Status
	// leaves this false.
	Written() bool
	// Send sets the HTTP response body without copying it.
	// From this point onward the body argument must not be changed.
	Send(body []byte) error
	// SendEarlyHints allows the server to hint to the browser what resources a page would need
	// so the browser can preload them while waiting for the server's full response. Only Link
	// headers already written to the response will be transmitted as Early Hints.
	//
	// This is a HTTP/2+ feature but all browsers will either understand it or safely ignore it.
	//
	// NOTE: Older HTTP/1.1 non-browser clients may face compatibility issues.
	//
	// See: https://developer.chrome.com/docs/web-platform/early-hints and
	// https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Link#syntax
	SendEarlyHints(hints []string) error
	// SendFile transfers the file from the specified path.
	// By default, the file is not compressed. To enable compression, set SendFile.Compress to true.
	// The Content-Type response HTTP header field is set based on the file's extension.
	// If the file extension is missing or invalid, the Content-Type is detected from the file's format.
	SendFile(file string, config ...SendFile) error
	// NoContent replies 204 No Content. SendStatus already discards the body for
	// every status statusDisallowsBody names; this drops the Content-Type as well,
	// since RFC 9110 Section 6.4.1 gives a 204 no content to describe.
	//
	// SendStatus(StatusNoContent) leaves a Content-Type a handler had set, so the
	// two are not interchangeable: this is the one that sends nothing about content.
	NoContent() error
	// SendStatus sets the HTTP status code and if the response body is empty,
	// it sets the correct status message in the body.
	SendStatus(status int) error
	// SendString sets the HTTP response body for string types.
	// This means no type assertion, recommended for faster performance
	SendString(body string) error
	// SendStream sets response body stream and optional body size.
	SendStream(stream io.Reader, size ...int) error
	// SendStreamWriter sets response body stream writer
	SendStreamWriter(streamWriter func(*bufio.Writer)) error
	// Set sets the response's HTTP header field to the specified key, value.
	Set(key, val string)
	setCanonical(key, val string)
	// Status sets the HTTP status for the response.
	// This method is chainable.
	Status(status int) Ctx
	// StatusCode returns the status code currently set on the response. It is the
	// read side of Status, and reports 200 until something sets another code.
	//
	// Called after Next it is the status the chain settled on, which is what
	// logging, metrics, and caching middleware key off.
	StatusCode() int
	// Type sets the Content-Type HTTP header to the MIME type specified by the file extension.
	Type(extension string, charset ...string) Ctx
	// Vary adds the given header field to the Vary response header.
	// This will append the header, if not already listed; otherwise, leaves it listed in the current location.
	// Per RFC 9110 Section 12.5.5 the wildcard "*" only has meaning as the sole member of the field:
	// once "*" is added (or already present), the header is collapsed to a single "*".
	Vary(fields ...string)
	// Write appends p into response body.
	Write(p []byte) (int, error)
	// Writef appends f & a into response body writer.
	Writef(f string, a ...any) (int, error)
	// WriteString appends s to response body.
	WriteString(s string) (int, error)
	// Drop closes the underlying connection without sending any response headers or body.
	// This can be useful for silently terminating client connections, such as in DDoS mitigation
	// or when blocking access to sensitive endpoints.
	Drop() error
	// End immediately flushes the current response and closes the underlying connection.
	//
	// Note: End does not work when using streaming (e.g. fasthttp's HijackConn or SendStream),
	// because in streaming mode the connection is managed asynchronously and ctx.Conn() may return nil.
	End() error
}
