// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package cache

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *cachedHeader) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "key":
			z.key, err = dc.ReadBytesLimit(z.key, 512)
			if err == nil && z.key == nil {
				z.key = []byte{}
			}
			if err != nil {
				err = msgp.WrapError(err, "key")
				return
			}
		case "value":
			z.value, err = dc.ReadBytesLimit(z.value, 16384)
			if err == nil && z.value == nil {
				z.value = []byte{}
			}
			if err != nil {
				err = msgp.WrapError(err, "value")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *cachedHeader) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "key"
	err = en.Append(0x82, 0xa3, 0x6b, 0x65, 0x79)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.key)
	if err != nil {
		err = msgp.WrapError(err, "key")
		return
	}
	// write "value"
	err = en.Append(0xa5, 0x76, 0x61, 0x6c, 0x75, 0x65)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.value)
	if err != nil {
		err = msgp.WrapError(err, "value")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *cachedHeader) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "key"
	o = append(o, 0x82, 0xa3, 0x6b, 0x65, 0x79)
	o = msgp.AppendBytes(o, z.key)
	// string "value"
	o = append(o, 0xa5, 0x76, 0x61, 0x6c, 0x75, 0x65)
	o = msgp.AppendBytes(o, z.value)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *cachedHeader) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "key":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadBytesHeader(bts)
			if err != nil {
				err = msgp.WrapError(err, "key")
				return
			}
			if zb0002 > 512 {
				err = msgp.ErrLimitExceeded
				return
			}
			if z.key == nil || uint32(cap(z.key)) < zb0002 {
				z.key = make([]byte, zb0002)
			} else {
				z.key = z.key[:zb0002]
			}
			if uint32(len(bts)) < zb0002 {
				err = msgp.ErrShortBytes
				return
			}
			copy(z.key, bts[:zb0002])
			bts = bts[zb0002:]
		case "value":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadBytesHeader(bts)
			if err != nil {
				err = msgp.WrapError(err, "value")
				return
			}
			if zb0003 > 16384 {
				err = msgp.ErrLimitExceeded
				return
			}
			if z.value == nil || uint32(cap(z.value)) < zb0003 {
				z.value = make([]byte, zb0003)
			} else {
				z.value = z.value[:zb0003]
			}
			if uint32(len(bts)) < zb0003 {
				err = msgp.ErrShortBytes
				return
			}
			copy(z.value, bts[:zb0003])
			bts = bts[zb0003:]
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *cachedHeader) Msgsize() (s int) {
	s = 1 + 4 + msgp.BytesPrefixSize + len(z.key) + 6 + msgp.BytesPrefixSize + len(z.value)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *item) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "headers":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "headers")
				return
			}
			if zb0002 > 1024 {
				err = msgp.ErrLimitExceeded
				return
			}
			if cap(z.headers) >= int(zb0002) {
				z.headers = (z.headers)[:zb0002]
			} else {
				z.headers = make([]cachedHeader, zb0002)
			}
			for za0001 := range z.headers {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "headers", za0001)
					return
				}
				if zb0003 > 1024 {
					err = msgp.ErrLimitExceeded
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "headers", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "key":
						z.headers[za0001].key, err = dc.ReadBytesLimit(z.headers[za0001].key, 512)
						if err == nil && z.headers[za0001].key == nil {
							z.headers[za0001].key = []byte{}
						}
						if err != nil {
							err = msgp.WrapError(err, "headers", za0001, "key")
							return
						}
					case "value":
						z.headers[za0001].value, err = dc.ReadBytesLimit(z.headers[za0001].value, 16384)
						if err == nil && z.headers[za0001].value == nil {
							z.headers[za0001].value = []byte{}
						}
						if err != nil {
							err = msgp.WrapError(err, "headers", za0001, "value")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "headers", za0001)
							return
						}
					}
				}
			}
		case "body":
			z.body, err = dc.ReadBytes(z.body)
			if err != nil {
				err = msgp.WrapError(err, "body")
				return
			}
		case "ctype":
			z.ctype, err = dc.ReadBytesLimit(z.ctype, 256)
			if err == nil && z.ctype == nil {
				z.ctype = []byte{}
			}
			if err != nil {
				err = msgp.WrapError(err, "ctype")
				return
			}
		case "cencoding":
			z.cencoding, err = dc.ReadBytesLimit(z.cencoding, 128)
			if err == nil && z.cencoding == nil {
				z.cencoding = []byte{}
			}
			if err != nil {
				err = msgp.WrapError(err, "cencoding")
				return
			}
		case "cacheControl":
			z.cacheControl, err = dc.ReadBytesLimit(z.cacheControl, 2048)
			if err == nil && z.cacheControl == nil {
				z.cacheControl = []byte{}
			}
			if err != nil {
				err = msgp.WrapError(err, "cacheControl")
				return
			}
		case "expires":
			z.expires, err = dc.ReadBytesLimit(z.expires, 128)
			if err == nil && z.expires == nil {
				z.expires = []byte{}
			}
			if err != nil {
				err = msgp.WrapError(err, "expires")
				return
			}
		case "etag":
			z.etag, err = dc.ReadBytesLimit(z.etag, 256)
			if err == nil && z.etag == nil {
				z.etag = []byte{}
			}
			if err != nil {
				err = msgp.WrapError(err, "etag")
				return
			}
		case "date":
			z.date, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "date")
				return
			}
		case "status":
			z.status, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "status")
				return
			}
		case "age":
			z.age, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "age")
				return
			}
		case "exp":
			z.exp, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "exp")
				return
			}
		case "ttl":
			z.ttl, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "ttl")
				return
			}
		case "forceRevalidate":
			z.forceRevalidate, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "forceRevalidate")
				return
			}
		case "revalidate":
			z.revalidate, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "revalidate")
				return
			}
		case "shareable":
			z.shareable, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "shareable")
				return
			}
		case "private":
			z.private, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "private")
				return
			}
		case "heapidx":
			z.heapidx, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "heapidx")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *item) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 17
	// write "headers"
	err = en.Append(0xde, 0x0, 0x11, 0xa7, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.headers)))
	if err != nil {
		err = msgp.WrapError(err, "headers")
		return
	}
	for za0001 := range z.headers {
		// map header, size 2
		// write "key"
		err = en.Append(0x82, 0xa3, 0x6b, 0x65, 0x79)
		if err != nil {
			return
		}
		err = en.WriteBytes(z.headers[za0001].key)
		if err != nil {
			err = msgp.WrapError(err, "headers", za0001, "key")
			return
		}
		// write "value"
		err = en.Append(0xa5, 0x76, 0x61, 0x6c, 0x75, 0x65)
		if err != nil {
			return
		}
		err = en.WriteBytes(z.headers[za0001].value)
		if err != nil {
			err = msgp.WrapError(err, "headers", za0001, "value")
			return
		}
	}
	// write "body"
	err = en.Append(0xa4, 0x62, 0x6f, 0x64, 0x79)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.body)
	if err != nil {
		err = msgp.WrapError(err, "body")
		return
	}
	// write "ctype"
	err = en.Append(0xa5, 0x63, 0x74, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.ctype)
	if err != nil {
		err = msgp.WrapError(err, "ctype")
		return
	}
	// write "cencoding"
	err = en.Append(0xa9, 0x63, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.cencoding)
	if err != nil {
		err = msgp.WrapError(err, "cencoding")
		return
	}
	// write "cacheControl"
	err = en.Append(0xac, 0x63, 0x61, 0x63, 0x68, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.cacheControl)
	if err != nil {
		err = msgp.WrapError(err, "cacheControl")
		return
	}
	// write "expires"
	err = en.Append(0xa7, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.expires)
	if err != nil {
		err = msgp.WrapError(err, "expires")
		return
	}
	// write "etag"
	err = en.Append(0xa4, 0x65, 0x74, 0x61, 0x67)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.etag)
	if err != nil {
		err = msgp.WrapError(err, "etag")
		return
	}
	// write "date"
	err = en.Append(0xa4, 0x64, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.date)
	if err != nil {
		err = msgp.WrapError(err, "date")
		return
	}
	// write "status"
	err = en.Append(0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.status)
	if err != nil {
		err = msgp.WrapError(err, "status")
		return
	}
	// write "age"
	err = en.Append(0xa3, 0x61, 0x67, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.age)
	if err != nil {
		err = msgp.WrapError(err, "age")
		return
	}
	// write "exp"
	err = en.Append(0xa3, 0x65, 0x78, 0x70)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.exp)
	if err != nil {
		err = msgp.WrapError(err, "exp")
		return
	}
	// write "ttl"
	err = en.Append(0xa3, 0x74, 0x74, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.ttl)
	if err != nil {
		err = msgp.WrapError(err, "ttl")
		return
	}
	// write "forceRevalidate"
	err = en.Append(0xaf, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x52, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteBool(z.forceRevalidate)
	if err != nil {
		err = msgp.WrapError(err, "forceRevalidate")
		return
	}
	// write "revalidate"
	err = en.Append(0xaa, 0x72, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteBool(z.revalidate)
	if err != nil {
		err = msgp.WrapError(err, "revalidate")
		return
	}
	// write "shareable"
	err = en.Append(0xa9, 0x73, 0x68, 0x61, 0x72, 0x65, 0x61, 0x62, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteBool(z.shareable)
	if err != nil {
		err = msgp.WrapError(err, "shareable")
		return
	}
	// write "private"
	err = en.Append(0xa7, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteBool(z.private)
	if err != nil {
		err = msgp.WrapError(err, "private")
		return
	}
	// write "heapidx"
	err = en.Append(0xa7, 0x68, 0x65, 0x61, 0x70, 0x69, 0x64, 0x78)
	if err != nil {
		return
	}
	err = en.WriteInt(z.heapidx)
	if err != nil {
		err = msgp.WrapError(err, "heapidx")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *item) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 17
	// string "headers"
	o = append(o, 0xde, 0x0, 0x11, 0xa7, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.headers)))
	for za0001 := range z.headers {
		// map header, size 2
		// string "key"
		o = append(o, 0x82, 0xa3, 0x6b, 0x65, 0x79)
		o = msgp.AppendBytes(o, z.headers[za0001].key)
		// string "value"
		o = append(o, 0xa5, 0x76, 0x61, 0x6c, 0x75, 0x65)
		o = msgp.AppendBytes(o, z.headers[za0001].value)
	}
	// string "body"
	o = append(o, 0xa4, 0x62, 0x6f, 0x64, 0x79)
	o = msgp.AppendBytes(o, z.body)
	// string "ctype"
	o = append(o, 0xa5, 0x63, 0x74, 0x79, 0x70, 0x65)
	o = msgp.AppendBytes(o, z.ctype)
	// string "cencoding"
	o = append(o, 0xa9, 0x63, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67)
	o = msgp.AppendBytes(o, z.cencoding)
	// string "cacheControl"
	o = append(o, 0xac, 0x63, 0x61, 0x63, 0x68, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c)
	o = msgp.AppendBytes(o, z.cacheControl)
	// string "expires"
	o = append(o, 0xa7, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73)
	o = msgp.AppendBytes(o, z.expires)
	// string "etag"
	o = append(o, 0xa4, 0x65, 0x74, 0x61, 0x67)
	o = msgp.AppendBytes(o, z.etag)
	// string "date"
	o = append(o, 0xa4, 0x64, 0x61, 0x74, 0x65)
	o = msgp.AppendUint64(o, z.date)
	// string "status"
	o = append(o, 0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	o = msgp.AppendInt(o, z.status)
	// string "age"
	o = append(o, 0xa3, 0x61, 0x67, 0x65)
	o = msgp.AppendUint64(o, z.age)
	// string "exp"
	o = append(o, 0xa3, 0x65, 0x78, 0x70)
	o = msgp.AppendUint64(o, z.exp)
	// string "ttl"
	o = append(o, 0xa3, 0x74, 0x74, 0x6c)
	o = msgp.AppendUint64(o, z.ttl)
	// string "forceRevalidate"
	o = append(o, 0xaf, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x52, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65)
	o = msgp.AppendBool(o, z.forceRevalidate)
	// string "revalidate"
	o = append(o, 0xaa, 0x72, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65)
	o = msgp.AppendBool(o, z.revalidate)
	// string "shareable"
	o = append(o, 0xa9, 0x73, 0x68, 0x61, 0x72, 0x65, 0x61, 0x62, 0x6c, 0x65)
	o = msgp.AppendBool(o, z.shareable)
	// string "private"
	o = append(o, 0xa7, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65)
	o = msgp.AppendBool(o, z.private)
	// string "heapidx"
	o = append(o, 0xa7, 0x68, 0x65, 0x61, 0x70, 0x69, 0x64, 0x78)
	o = msgp.AppendInt(o, z.heapidx)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *item) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "headers":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "headers")
				return
			}
			if zb0002 > 1024 {
				err = msgp.ErrLimitExceeded
				return
			}
			if cap(z.headers) >= int(zb0002) {
				z.headers = (z.headers)[:zb0002]
			} else {
				z.headers = make([]cachedHeader, zb0002)
			}
			for za0001 := range z.headers {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "headers", za0001)
					return
				}
				if zb0003 > 1024 {
					err = msgp.ErrLimitExceeded
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "headers", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "key":
						var zb0004 uint32
						zb0004, bts, err = msgp.ReadBytesHeader(bts)
						if err != nil {
							err = msgp.WrapError(err, "headers", za0001, "key")
							return
						}
						if zb0004 > 512 {
							err = msgp.ErrLimitExceeded
							return
						}
						if z.headers[za0001].key == nil || uint32(cap(z.headers[za0001].key)) < zb0004 {
							z.headers[za0001].key = make([]byte, zb0004)
						} else {
							z.headers[za0001].key = z.headers[za0001].key[:zb0004]
						}
						if uint32(len(bts)) < zb0004 {
							err = msgp.ErrShortBytes
							return
						}
						copy(z.headers[za0001].key, bts[:zb0004])
						bts = bts[zb0004:]
					case "value":
						var zb0005 uint32
						zb0005, bts, err = msgp.ReadBytesHeader(bts)
						if err != nil {
							err = msgp.WrapError(err, "headers", za0001, "value")
							return
						}
						if zb0005 > 16384 {
							err = msgp.ErrLimitExceeded
							return
						}
						if z.headers[za0001].value == nil || uint32(cap(z.headers[za0001].value)) < zb0005 {
							z.headers[za0001].value = make([]byte, zb0005)
						} else {
							z.headers[za0001].value = z.headers[za0001].value[:zb0005]
						}
						if uint32(len(bts)) < zb0005 {
							err = msgp.ErrShortBytes
							return
						}
						copy(z.headers[za0001].value, bts[:zb0005])
						bts = bts[zb0005:]
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "headers", za0001)
							return
						}
					}
				}
			}
		case "body":
			z.body, bts, err = msgp.ReadBytesBytes(bts, z.body)
			if err != nil {
				err = msgp.WrapError(err, "body")
				return
			}
		case "ctype":
			var zb0006 uint32
			zb0006, bts, err = msgp.ReadBytesHeader(bts)
			if err != nil {
				err = msgp.WrapError(err, "ctype")
				return
			}
			if zb0006 > 256 {
				err = msgp.ErrLimitExceeded
				return
			}
			if z.ctype == nil || uint32(cap(z.ctype)) < zb0006 {
				z.ctype = make([]byte, zb0006)
			} else {
				z.ctype = z.ctype[:zb0006]
			}
			if uint32(len(bts)) < zb0006 {
				err = msgp.ErrShortBytes
				return
			}
			copy(z.ctype, bts[:zb0006])
			bts = bts[zb0006:]
		case "cencoding":
			var zb0007 uint32
			zb0007, bts, err = msgp.ReadBytesHeader(bts)
			if err != nil {
				err = msgp.WrapError(err, "cencoding")
				return
			}
			if zb0007 > 128 {
				err = msgp.ErrLimitExceeded
				return
			}
			if z.cencoding == nil || uint32(cap(z.cencoding)) < zb0007 {
				z.cencoding = make([]byte, zb0007)
			} else {
				z.cencoding = z.cencoding[:zb0007]
			}
			if uint32(len(bts)) < zb0007 {
				err = msgp.ErrShortBytes
				return
			}
			copy(z.cencoding, bts[:zb0007])
			bts = bts[zb0007:]
		case "cacheControl":
			var zb0008 uint32
			zb0008, bts, err = msgp.ReadBytesHeader(bts)
			if err != nil {
				err = msgp.WrapError(err, "cacheControl")
				return
			}
			if zb0008 > 2048 {
				err = msgp.ErrLimitExceeded
				return
			}
			if z.cacheControl == nil || uint32(cap(z.cacheControl)) < zb0008 {
				z.cacheControl = make([]byte, zb0008)
			} else {
				z.cacheControl = z.cacheControl[:zb0008]
			}
			if uint32(len(bts)) < zb0008 {
				err = msgp.ErrShortBytes
				return
			}
			copy(z.cacheControl, bts[:zb0008])
			bts = bts[zb0008:]
		case "expires":
			var zb0009 uint32
			zb0009, bts, err = msgp.ReadBytesHeader(bts)
			if err != nil {
				err = msgp.WrapError(err, "expires")
				return
			}
			if zb0009 > 128 {
				err = msgp.ErrLimitExceeded
				return
			}
			if z.expires == nil || uint32(cap(z.expires)) < zb0009 {
				z.expires = make([]byte, zb0009)
			} else {
				z.expires = z.expires[:zb0009]
			}
			if uint32(len(bts)) < zb0009 {
				err = msgp.ErrShortBytes
				return
			}
			copy(z.expires, bts[:zb0009])
			bts = bts[zb0009:]
		case "etag":
			var zb0010 uint32
			zb0010, bts, err = msgp.ReadBytesHeader(bts)
			if err != nil {
				err = msgp.WrapError(err, "etag")
				return
			}
			if zb0010 > 256 {
				err = msgp.ErrLimitExceeded
				return
			}
			if z.etag == nil || uint32(cap(z.etag)) < zb0010 {
				z.etag = make([]byte, zb0010)
			} else {
				z.etag = z.etag[:zb0010]
			}
			if uint32(len(bts)) < zb0010 {
				err = msgp.ErrShortBytes
				return
			}
			copy(z.etag, bts[:zb0010])
			bts = bts[zb0010:]
		case "date":
			z.date, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "date")
				return
			}
		case "status":
			z.status, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "status")
				return
			}
		case "age":
			z.age, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "age")
				return
			}
		case "exp":
			z.exp, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "exp")
				return
			}
		case "ttl":
			z.ttl, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ttl")
				return
			}
		case "forceRevalidate":
			z.forceRevalidate, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "forceRevalidate")
				return
			}
		case "revalidate":
			z.revalidate, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "revalidate")
				return
			}
		case "shareable":
			z.shareable, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "shareable")
				return
			}
		case "private":
			z.private, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "private")
				return
			}
		case "heapidx":
			z.heapidx, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "heapidx")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *item) Msgsize() (s int) {
	s = 3 + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.headers {
		s += 1 + 4 + msgp.BytesPrefixSize + len(z.headers[za0001].key) + 6 + msgp.BytesPrefixSize + len(z.headers[za0001].value)
	}
	s += 5 + msgp.BytesPrefixSize + len(z.body) + 6 + msgp.BytesPrefixSize + len(z.ctype) + 10 + msgp.BytesPrefixSize + len(z.cencoding) + 13 + msgp.BytesPrefixSize + len(z.cacheControl) + 8 + msgp.BytesPrefixSize + len(z.expires) + 5 + msgp.BytesPrefixSize + len(z.etag) + 5 + msgp.Uint64Size + 7 + msgp.IntSize + 4 + msgp.Uint64Size + 4 + msgp.Uint64Size + 4 + msgp.Uint64Size + 16 + msgp.BoolSize + 11 + msgp.BoolSize + 10 + msgp.BoolSize + 8 + msgp.BoolSize + 8 + msgp.IntSize
	return
}
