name: Dependabot auto-merge

on:
  workflow_dispatch:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    uses: gofiber/.github/.github/workflows/dependabot-automerge.yml@main
    with:
      match_pattern: '^unit|^lint /'
    secrets:
      github-token: ${{ secrets.PR_TOKEN }}
