name: Dependabot auto-merge
on:
  workflow_dispatch:
  pull_request_target:
permissions:
  contents: write
  pull-requests: write
jobs:
  wait_for_checks:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Wait for check is finished
        id: wait_for_checks
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.PR_TOKEN }}
          match_pattern: ^unit
          interval: 10
          timeout: 600
  dependabot:
    needs: [wait_for_checks]
    name: Dependabot auto-merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3.1.0
        with:
          github-token: "${{ secrets.PR_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.PR_TOKEN}}
