name: Linter

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    uses: gofiber/.github/.github/workflows/go-lint-single.yml@main
