name: markdownlint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
  pull_request:
    paths:
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Fetch Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe # v24.1.0
        with:
          globs: |
            **/*.md
            #vendor
