name: markdownlint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
  pull_request:
    paths:
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Fetch Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
        with:
          globs: |
            **/*.md
            #vendor
