name: markdownlint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
  pull_request:
    paths:
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    timeout-minutes: 10
    steps:
      - name: Fetch Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
        with:
          globs: |
            **/*.md
            #vendor
            #.github/issue-replies
