name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit:
    strategy:
      matrix:
        go-version: [1.25.x, 1.26.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
      - name: Fetch Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        uses: gofiber/.github/.github/actions/gotestsum@main
        with:
          packages: ./...
          rerun-fails: '2'
          args: -race -count=1 -coverprofile=coverage.txt -covermode=atomic -shuffle=on

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.25.x' }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          slug: gofiber/fiber
          verbose: true

  repeated:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Fetch Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable

      - name: Test
        uses: gofiber/.github/.github/actions/gotestsum@main
        with:
          args: ./... -race -count=15 -shuffle=on
