name: workflow-lint

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - ".github/actionlint.yaml"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - ".github/actionlint.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    uses: gofiber/.github/.github/workflows/workflow-lint.yml@main
